/**
 * The challenge catalog: every measurable "çelınc" the app offers.
 *
 * Generated from the product design pass and reviewed by hand. Each entry has
 * to be measurable on a phone — see `howMeasuredTr` — and carries anti-abuse
 * caps used by the server when validating entries.
 */
import type { ChallengeType, MetricType } from './types';

export const CHALLENGE_TYPES: readonly ChallengeType[] = [
  {
    key: "adim_yarisi",
    nameTr: "Adım Yarışı",
    emoji: "🚶",
    metricType: "auto_steps",
    unitTr: "adım",
    direction: "higher",
    descriptionTr: "Kim daha çok yürüdüyse o kazanır. Telefon cebinde durduğu sürece sayıyor.",
    descriptionPoliteTr: "Süre boyunca en çok adım atan kazanır. Telefonunuzu yanınızda taşımanız yeterli.",
    howMeasuredTr: "Telefonun kendi adım sayacından okunuyor, günde bir kere uygulamayı açman yeterli. Android'de Health Connect bağlı değilse adımlar sadece uygulama açıkken sayılır, o gün adımını elle de girebilirsin.",
    defaultDurationDays: 3,
    suggestedRewardTr: "Kaybeden herkese döner ısmarlar.",
    antiCheatTr: "Hile: telefonu çamaşır makinesine bantlamak, köpeğin tasmasına takmak, elle sallamak. Caydırma: saatlik adım dağılımı sunucuda tutulur; 1 saatte 12.000+ adım gibi imkânsız sıçramalar 'şüpheli' bayrağı alır (hızlı koşucu bile saatte 10 bin civarı atar) ve arkadaşlar itiraz açabilir. İtiraz kazanırsa o günün adımı silinir. Sadece tek cihaz bağlanabilir; çelınc sırasında cihaz değişirse önceki günler kilitlenir.",
    proofRequired: false,
    category: "hareket",
    maxPerEntry: 100000,
    maxPerDay: 100000,
  },
  {
    key: "kosu_km",
    nameTr: "Koşu Kilometresi",
    emoji: "🏃",
    metricType: "manual_count",
    unitTr: "km",
    direction: "higher",
    descriptionTr: "Süre sonunda en çok kilometre koşan kazanır. Yürüyüş koşu değil, ikimiz de biliyoruz.",
    descriptionPoliteTr: "Süre boyunca en çok kilometre koşan kazanır. Koşu uygulamanızdan bir ekran görüntüsü yeterli.",
    howMeasuredTr: "Her koşudan sonra kaç kilometre olduğunu sen giriyorsun ve koşu uygulamandan ekran görüntüsü ekliyorsun. Ekran görüntüsü olmayan giriş sayılmıyor.",
    defaultDurationDays: 7,
    suggestedRewardTr: "Kaybeden, kazananın yeni koşu ayakkabısına 200 lira katkı yapar.",
    antiCheatTr: "Hile: bisikletle koşu kaydı, eski koşunun ekran görüntüsü, arabayla 'koşmak'. Caydırma: fotoğraf kanıtı zorunlu, ekran görüntüsünde tarih ve tempo görünmeli; 2:30 dk/km altındaki tempo otomatik şüpheli işaretlenir; günde 42 km üstü şüpheli. Arkadaşlar itiraz eder, çoğunluk 'hile' derse giriş silinir ve o gün 0 sayılır.",
    proofRequired: true,
    category: "hareket",
    maxPerEntry: 60,
    maxPerDay: 100,
  },
  {
    key: "sinav_sayisi",
    nameTr: "Şınav Kapışması",
    emoji: "💪",
    metricType: "manual_count",
    unitTr: "tekrar",
    direction: "higher",
    descriptionTr: "Her gün kaç şınav çektiysen giriyorsun, toplamı en yüksek olan kazanır. Dizden çekince sayılmıyor lan.",
    descriptionPoliteTr: "Günlük şınav sayınızı girin, süre sonunda toplamı en yüksek olan kazanır. Kısa bir video istenebilir.",
    howMeasuredTr: "Setleri sen giriyorsun, uygulama günlük toplamı tutuyor. Günde en az bir set için uygulamanın kamerasından kısa bir video çekmen gerekiyor.",
    defaultDurationDays: 7,
    suggestedRewardTr: "Kaybeden bir gün boyunca kazananın seçtiği profil fotoğrafını kullanır.",
    antiCheatTr: "Hile: hava sayısı girmek, yarım şınav, hızlandırılmış video. Caydırma: kanıt videosu zorunlu; sunucu video süresini o setin beyan edilen sayısıyla karşılaştırır (saniyede 1,5 şınavdan fazlası şüpheli: 12 saniyelik videoda 40 şınav olmaz). Arkadaşlar 'form bozuk' itirazı açabilir; itiraz kabul edilirse set yarıya indirilir.",
    proofRequired: true,
    category: "hareket",
    maxPerEntry: 150,
    maxPerDay: 300,
  },
  {
    key: "merdiven_kati",
    nameTr: "Merdiven Canavarı",
    emoji: "🪜",
    metricType: "manual_count",
    unitTr: "kat",
    direction: "higher",
    descriptionTr: "Asansöre binmek yok. Çıktığın her kat sayılıyor, en çok tırmanan kazanır.",
    descriptionPoliteTr: "Asansör yerine merdiven kullanın ve çıktığınız katları girin. En çok kat tırmanan kazanır.",
    howMeasuredTr: "Çıktığın kat sayısını sen giriyorsun, inmek sayılmıyor. Telefon bunu kendi başına ölçemiyor, grup isterse merdiven fotoğrafı zorunlu olabilir.",
    defaultDurationDays: 5,
    suggestedRewardTr: "Kaybedenler kazananın alışveriş poşetlerini bir kere yukarı taşır.",
    antiCheatTr: "Hile: aşağı inerken sayı yazmak, yürüyen merdiven, hava sayısı. Caydırma: günlük 60 kat tavanı; tek girişte 20 kat üstü 'şüpheli' işaretlenir ve fotoğraf ister; arkadaşlar itiraz edebilir, çoğunluk hile derse gün sıfırlanır.",
    proofRequired: false,
    category: "hareket",
    maxPerEntry: 30,
    maxPerDay: 60,
  },
  {
    key: "odak_seansi",
    nameTr: "Odak Seansı",
    emoji: "🎯",
    metricType: "focus_minutes",
    unitTr: "dk",
    direction: "higher",
    descriptionTr: "Sayacı başlatıp telefonu bırakıyorsun. Instagram'a bakmak için çıkarsan seans yanar, en çok dakika biriktiren kazanır.",
    descriptionPoliteTr: "Uygulamadaki odak sayacını başlatın ve telefona dokunmayın. En çok odak dakikası toplayan kazanır.",
    howMeasuredTr: "Süreyi uygulamanın kendi sayacı tutuyor. Başka bir uygulamaya geçersen veya telefonu kilitlersen seans bozulur ve o dakikalar sayılmaz.",
    defaultDurationDays: 7,
    suggestedRewardTr: "Kaybedenler kazananın seçtiği filmi hep beraber izler.",
    antiCheatTr: "Hile: ikinci telefondan scroll'lamak, seansı açıp uyumak veya telefonu bırakıp gitmek. Caydırma: seans sırasında rastgele aralıklarla (20-40 dk) ekranda 'Buradayım' butonu çıkar, 60 sn içinde basılmazsa seans o anda biter ve sadece o ana kadarki süre sayılır; günlük 6 saat tavanı; ikinci telefonun teknik tespiti yok, arkadaşlar 'o saatte bizimle mesajlaşıyordu' itirazını ekran görüntüsüyle açar, çoğunluk hile derse seans silinir.",
    proofRequired: false,
    category: "ekran",
    maxPerEntry: 180,
    maxPerDay: 360,
  },
  {
    key: "ekran_suresi_beyani",
    nameTr: "Ekran Süresi Düellosu",
    emoji: "📱",
    metricType: "manual_lower_is_better",
    unitTr: "dk",
    direction: "lower",
    descriptionTr: "Her gece ekran süreni ekran görüntüsüyle giriyorsun. Ortalaması en düşük olan kazanır, günde sekiz saat TikTok izleyen baştan kaybetmiş.",
    descriptionPoliteTr: "Her gün cihazınızın ekran süresi raporundaki toplam dakikayı girin ve ekran görüntüsünü ekleyin. En düşük ortalama kazanır.",
    howMeasuredTr: "Uygulama ekran süreni kendi okuyamıyor, o yüzden iOS'ta Ekran Süresi ya da Android'de Dijital Denge ekranındaki toplamı ekran görüntüsüyle sen giriyorsun. Girmediğin gün 1440 dakika yazılıyor.",
    defaultDurationDays: 7,
    suggestedRewardTr: "Kaybeden bir hafta boyunca grupta 'Ekran Kölesi' olarak görünür.",
    antiCheatTr: "Hile: sahte veya eski ekran görüntüsü, ikinci cihazda kullanım, hiç girmemek. Caydırma: ekran görüntüsünde o günün tarihi görünmeli; girilmeyen gün otomatik 1440 dk; arkadaşlar ekran görüntüsünü inceleyip itiraz açar, çoğunluk hile derse o gün 1440 dk yazılır.",
    proofRequired: true,
    category: "ekran",
    maxPerEntry: 1440,
    maxPerDay: 1440,
    missingDayPenalty: 1440,
  },
  {
    key: "sosyal_medya_orucu",
    nameTr: "Sosyal Medya Orucu",
    emoji: "🚫",
    metricType: "daily_boolean",
    unitTr: "gün",
    direction: "higher",
    descriptionTr: "Instagram, TikTok, X, hiçbiri yok. Her akşam girmediğini işaretliyorsun.",
    descriptionPoliteTr: "Belirlenen sosyal medya uygulamalarına girmediğiniz günleri işaretleyin. En çok temiz gün toplayan kazanır.",
    howMeasuredTr: "Her gün girdim ya da girmedim diye işaretliyorsun, akşam da ekran süresi listenden bir görüntü ekliyorsun. İşaretlemediğin gün girmiş sayılıyorsun.",
    defaultDurationDays: 7,
    suggestedRewardTr: "Kaybeden bir hafta boyunca kazananın her dediğine 'haklısın abi' der.",
    antiCheatTr: "Hile: tarayıcıdan girmek, ikinci telefon, uygulamayı silip yeniden yüklemek. Caydırma: ekran görüntüsü kanıtı zorunlu, tarayıcı süresi de listede görünür; arkadaşlar bir story izlenmesi veya beğeni görürse ekran görüntüsüyle itiraz açar, itiraz kabul edilirse o gün 'girdi' sayılır.",
    proofRequired: true,
    category: "ekran",
    maxPerEntry: 1,
    maxPerDay: 1,
  },
  {
    key: "erken_kus",
    nameTr: "Erken Kalkan Koyar",
    emoji: "🌅",
    metricType: "checkin_deadline",
    unitTr: "gün",
    direction: "higher",
    descriptionTr: "Her sabah yediden önce uygulamayı açıp 'kalktım' diyeceksin. Bir dakika geç kalsan o gün gitti, en çok sabah yakalayan kazanır.",
    descriptionPoliteTr: "Her sabah belirlenen saatten önce uygulamadan 'kalktım' check-in'i yapın. En çok başarılı sabah toplayan kazanır.",
    howMeasuredTr: "Sabah check-in butonuna basıyorsun. Saati telefonun değil sunucu belirlediği için saatle oynamak işe yaramıyor, geç kalan check-in de sayılmıyor.",
    defaultDurationDays: 5,
    defaultDeadlineTime: "07:00",
    suggestedRewardTr: "Kaybeden kazanana bir sabah kahvaltı getirir.",
    antiCheatTr: "Hile: telefon saatini geri almak, alarmla check-in yapıp yatağa dönmek, hiç yatmadan 'kalktım' demek. Caydırma: sunucu saati esas alınır, cihaz saati önemsiz; en erken 04:00; grup 'selfie zorunlu' modunu açabilir (gün ışığında, uygulama içi kamera); adım verisi olan cihazlarda (iOS CoreMotion / Health Connect) check-in sonrası 60 dk içinde 300 adım yoksa 'şüpheli' işareti. Arkadaşlar 'bu selfie yataktan çekilmiş' itirazı açabilir.",
    proofRequired: false,
    category: "uyku",
    maxPerEntry: 1,
    maxPerDay: 1,
  },
  {
    key: "erken_yat",
    nameTr: "Erken Yatma Sözü",
    emoji: "🌙",
    metricType: "checkin_deadline",
    unitTr: "gün",
    direction: "higher",
    descriptionTr: "23:00'ten önce 'yattım' deyip telefonu bırakacaksın. Gece ikide hâlâ Reels'teysen o gece sayılmaz, en çok erken gece toplayan kazanır.",
    descriptionPoliteTr: "Her gece belirlenen saatten önce 'yatıyorum' check-in'i yapın. En çok başarılı gece toplayan kazanır.",
    howMeasuredTr: "Akşam 'yatıyorum' butonuna basıyorsun, saati sunucu tutuyor. Check-in'den sonra uygulamada dolaşırsan o gece iptal oluyor, ama telefonda başka ne yaptığını uygulama göremiyor.",
    defaultDurationDays: 7,
    defaultDeadlineTime: "23:00",
    suggestedRewardTr: "Kaybeden bir hafta boyunca her gece 23:00'te kazanana iyi geceler mesajı atar.",
    antiCheatTr: "Hile: check-in yapıp telefonda takılmaya devam etmek. Caydırma: sunucu saati; check-in sonrası gece uygulama kullanılırsa gece iptal; arkadaşlar gece 01:00'de 'çevrimiçi' veya yeni story görürse ekran görüntüsüyle itiraz açar, çoğunluk kabul ederse gece düşer; isteğe bağlı 'kanıt modu': ertesi sabah uyku uygulaması veya Ekran Süresi'nin gece saatleri ekran görüntüsü.",
    proofRequired: false,
    category: "uyku",
    maxPerEntry: 1,
    maxPerDay: 1,
  },
  {
    key: "su_bardak",
    nameTr: "Su Bardağı Yarışı",
    emoji: "💧",
    metricType: "manual_count",
    unitTr: "bardak",
    direction: "higher",
    descriptionTr: "İçtiğin her bardağı giriyorsun, sonunda toplamı en yüksek olan kazanır. Çay kahve sayılmıyor lan, su dedik.",
    descriptionPoliteTr: "İçtiğiniz her su bardağını girin, toplamı en yüksek olan kazanır. Çay ve kahve sayılmaz.",
    howMeasuredTr: "Her bardak için artı butonuna basıyorsun, bir bardak 250 ml sayılıyor. Gün içinde rastgele bir saatte bardağının fotoğrafı isteniyor, beş dakika içinde göndermezsen o günün yarısı gidiyor.",
    defaultDurationDays: 7,
    suggestedRewardTr: "Kaybedenler kazanana bir damacana su alır.",
    antiCheatTr: "Hile: içmeden basmak, gece yarısı 15 bardak birden girmek. Caydırma: bardaklar arası minimum 20 dk aralık (sunucu zamanı); günlük 15 bardak tavanı; rastgele fotoğraf isteğine 5 dk içinde cevap gelmezse o gün yarıya iner. Arkadaşlar itiraz edebilir.",
    proofRequired: false,
    category: "beslenme",
    maxPerEntry: 10,
    maxPerDay: 30,
  },
  {
    key: "sekersiz_gun",
    nameTr: "Şekersiz Günler",
    emoji: "🍬",
    metricType: "daily_boolean",
    unitTr: "gün",
    direction: "higher",
    descriptionTr: "Tatlı yok, kola yok. Her akşam şeker yemediğini işaretliyorsun.",
    descriptionPoliteTr: "Her gün şekerli yiyecek ve içecek tüketmediğinizi işaretleyin. En çok temiz gün toplayan kazanır.",
    howMeasuredTr: "Her gün işaretliyorsun, işaretlemediğin gün yemiş sayılıyorsun. Zorunlu kanıt yok, isteyen öğün fotoğrafı ekleyebilir.",
    defaultDurationDays: 7,
    suggestedRewardTr: "Kaybeden herkese tatlı ısmarlar ama kendisi yemez.",
    antiCheatTr: "Hile: gizli gizli yemek, 'şekersiz' etiketli ama şekerli şeyler. Caydırma: dürüstlük sistemi + itiraz. Arkadaşlar ellerinde fotoğraf/story varsa (elinde kola ile görüldüyse) itiraz açar; çoğunluk 'yedi' derse gün düşer. Sunucu itirazın kanıt fotoğrafını saklar.",
    proofRequired: false,
    category: "beslenme",
    maxPerEntry: 1,
    maxPerDay: 1,
  },
  {
    key: "fast_food_yok",
    nameTr: "Fast Food Boykotu",
    emoji: "🍔",
    metricType: "daily_boolean",
    unitTr: "gün",
    direction: "higher",
    descriptionTr: "Hamburger, pizza, gece dürümü yok. En çok temiz gün toplayan kazanır, kapıya kurye gelen o günü kaybeder.",
    descriptionPoliteTr: "Her gün fast food yemediğinizi işaretleyin. En çok temiz gün toplayan kazanır.",
    howMeasuredTr: "Her gün işaretliyorsun, işaretlemediğin gün yemiş sayılıyorsun. Grup isterse öğün fotoğrafı zorunlu hale getirilebilir.",
    defaultDurationDays: 7,
    suggestedRewardTr: "Kaybeden kazanana kendi eliyle bir ev yemeği yapar.",
    antiCheatTr: "Hile: yemek sipariş uygulamasından gizlice sipariş vermek. Caydırma: arkadaşlar itiraz açabilir (siparişin fotoğrafı, story, ortak sipariş geçmişi); çoğunluk kararıyla o gün düşer. 'Fotoğraf zorunlu' modunda fotoğraf gelmeyen gün otomatik 'yedi' sayılır.",
    proofRequired: false,
    category: "beslenme",
    maxPerEntry: 1,
    maxPerDay: 1,
  },
  {
    key: "sebze_meyve_porsiyon",
    nameTr: "Yeşillik Kotası",
    emoji: "🥦",
    metricType: "manual_count",
    unitTr: "porsiyon",
    direction: "higher",
    descriptionTr: "Yediğin sebze ve meyve porsiyonlarını giriyorsun, en çok toplayan kazanır. Dönerin içindeki marul porsiyon değil.",
    descriptionPoliteTr: "Yediğiniz sebze ve meyve porsiyonlarını girin. Süre sonunda toplamı en yüksek olan kazanır.",
    howMeasuredTr: "Her porsiyon için artı butonuna basıyorsun, bir porsiyon bir avuç ya da bir orta boy meyve demek. Her porsiyonda uygulamanın kamerasından tabak fotoğrafı isteniyor.",
    defaultDurationDays: 7,
    suggestedRewardTr: "Kaybeden kazanana bir meyve sepeti alır.",
    antiCheatTr: "Hile: aynı tabağı 3 kez fotoğraflamak, internetten fotoğraf indirmek. Caydırma: fotoğraf sadece uygulama içi kameradan (galeriden yükleme yok), sunucu zaman damgası ekler; birebir aynı görüntünün tekrarı hash ile yakalanır, benzer fotoğraflar için arkadaş itirazı; çoğunluk hile derse porsiyon silinir.",
    proofRequired: true,
    category: "beslenme",
    maxPerEntry: 8,
    maxPerDay: 15,
  },
  {
    key: "kitap_sayfa",
    nameTr: "Sayfa Avcısı",
    emoji: "📚",
    metricType: "manual_count",
    unitTr: "sayfa",
    direction: "higher",
    descriptionTr: "Okuduğun sayfaları giriyorsun, süre sonunda en çok sayfa deviren kazanır. Story okumak sayfa sayılmıyor kanka.",
    descriptionPoliteTr: "Okuduğunuz sayfaları girin, en çok sayfa okuyan kazanır. Basılı kitap da e-kitap da olur.",
    howMeasuredTr: "Kitabı seçip her okuma sonunda kaldığın sayfayı giriyorsun, uygulama farkı kendisi hesaplıyor. Her girişte kaldığın sayfanın fotoğrafını çekmen gerekiyor.",
    defaultDurationDays: 14,
    suggestedRewardTr: "Kaybeden kazanana istediği kitabı alır.",
    antiCheatTr: "Hile: 'bugün 300 sayfa okudum' yazmak, kitabı rastgele açıp fotoğraf çekmek. Caydırma: fotoğraf zorunlu, sayfa numarası kitap başına geriye gidemez; günde 150 sayfa üstü otomatik 'şüpheli' işareti; arkadaşlar 'o bölümde ne oluyor, anlat' itirazı açar, cevap gelmezse veya çoğunluk inanmazsa giriş silinir.",
    proofRequired: true,
    category: "zihin",
    maxPerEntry: 300,
    maxPerDay: 500,
  },
  {
    key: "dil_pratigi",
    nameTr: "Dil Pratiği Dakikası",
    emoji: "🔤",
    metricType: "manual_count",
    unitTr: "dk",
    direction: "higher",
    descriptionTr: "Kaç dakika dil çalıştıysan gir, uygulamandan ekran görüntüsünü de at. En çok dakika toplayan kazanır.",
    descriptionPoliteTr: "Her gün yabancı dil çalışma dakikanızı girin ve dil uygulamanızdan ekran görüntüsü ekleyin. En çok dakika toplayan kazanır.",
    howMeasuredTr: "Dakikayı sen giriyorsun, yanına o günün ilerlemesini gösteren bir ekran görüntüsü ekliyorsun. Görüntü dakikayı değil o gün çalıştığını gösteriyor, gelmediği gün sıfır sayılıyor.",
    defaultDurationDays: 14,
    suggestedRewardTr: "Kaybeden kazananın dil uygulaması aboneliğini bir ay öder.",
    antiCheatTr: "Hile: uygulamayı açık bırakıp dakika saymak, eski ekran görüntüsü, 5 dk çalışıp 120 yazmak. Caydırma: ekran görüntüsünde o günün ilerlemesi (XP/ders/seri) görünmeli; günlük 120 dk tavanı; ilerlemeye göre orantısız dakika (10 XP'ye 120 dk gibi) arkadaş itirazına açıktır, çoğunluk hile derse gün yarıya iner.",
    proofRequired: true,
    category: "zihin",
    maxPerEntry: 120,
    maxPerDay: 240,
  },
  {
    key: "gunluk_yazma",
    nameTr: "Günlük Defteri",
    emoji: "📝",
    metricType: "daily_boolean",
    unitTr: "gün",
    direction: "higher",
    descriptionTr: "Her gün en az yarım sayfa yazıp fotoğrafını atıyorsun. 'Bugün iyiydi' yazıp kapatmak olmuyor, en çok yazılı gün toplayan kazanır.",
    descriptionPoliteTr: "Her gün en az yarım sayfa günlük yazın ve sayfanın fotoğrafını çekin. En çok yazılı gün toplayan kazanır.",
    howMeasuredTr: "Her gün 'yazdım' diye işaretleyip sayfanın fotoğrafını çekiyorsun. Yazdıkların okunmasın diye fotoğraf gruba bulanık gösteriliyor, sadece sayfanın dolu olduğu görünüyor.",
    defaultDurationDays: 14,
    suggestedRewardTr: "Kaybeden kazanana güzel bir defter alır.",
    antiCheatTr: "Hile: eski sayfayı fotoğraflamak, iki satır yazıp 'yazdım' demek. Caydırma: fotoğraf sadece uygulama içi kameradan, sunucu zaman damgası ekler, birebir aynı fotoğrafın tekrarı hash ile yakalanır; sayfada tarih görünmeli; arkadaşlar 'sayfa boş' itirazı açabilir, çoğunluk kabul ederse gün düşer.",
    proofRequired: true,
    category: "zihin",
    maxPerEntry: 1,
    maxPerDay: 1,
  },
  {
    key: "sigara_yok",
    nameTr: "Dumansız Günler",
    emoji: "🚭",
    metricType: "daily_boolean",
    unitTr: "gün",
    direction: "higher",
    descriptionTr: "Her gün içmediğini işaretliyorsun. Bir tane bile çektiysen o gün gitti, en çok temiz gün toplayan kazanır.",
    descriptionPoliteTr: "Her gün sigara içmediğinizi işaretleyin. En çok temiz gün toplayan kazanır, zor olduğunu biliyoruz.",
    howMeasuredTr: "Her gün içtim ya da içmedim diye işaretliyorsun, işaretlemediğin gün içmiş sayılıyorsun. Uygulamanın bunu doğrulama şansı yok, sadece arkadaşların itiraz edebiliyor.",
    defaultDurationDays: 14,
    suggestedRewardTr: "Kaybeden kazanana bir aylık sigara parası kadar hediye alır.",
    antiCheatTr: "Hile: gizli içmek. Caydırma: dürüstlük + arkadaş itirazı (story, birlikte görülme, fotoğraf); çoğunluk 'içti' derse gün düşer. Kanıt modunda 22:00 selfie'si gelmeyen gün 'içti' sayılır. Yalan söyleyen kendi kendine koymuş olur.",
    proofRequired: false,
    category: "kotu_aliskanlik",
    maxPerEntry: 1,
    maxPerDay: 1,
  },
  {
    key: "alkol_yok",
    nameTr: "Ayık Kalma Yarışı",
    emoji: "🍺",
    metricType: "daily_boolean",
    unitTr: "gün",
    direction: "higher",
    descriptionTr: "Her gün içmediğini işaretliyorsun, en çok ayık gün toplayan kazanır. 'Cuma akşamı bir bira bir şey olmaz' diyen o günü kaybeder.",
    descriptionPoliteTr: "Her gün alkol almadığınızı işaretleyin. En çok temiz gün toplayan kazanır.",
    howMeasuredTr: "Her gün işaretliyorsun, işaretlemediğin gün içmiş sayılıyorsun. Grup isterse akşamları selfie isteyen kanıt modunu açabilir.",
    defaultDurationDays: 14,
    suggestedRewardTr: "Kaybeden bir sonraki buluşmada alkolsüz içecekleri ısmarlar.",
    antiCheatTr: "Hile: gizli içmek, işaretlemeyi 'unutmak'. Caydırma: işaretlenmeyen gün otomatik düşer; arkadaşlar story/fotoğraf ile itiraz açar, çoğunluk kararıyla gün düşer. Kanıt modu açıksa 22:00 selfie'si gelmeyen gün 'içti' sayılır.",
    proofRequired: false,
    category: "kotu_aliskanlik",
    maxPerEntry: 1,
    maxPerDay: 1,
  },
  {
    key: "tirnak_yeme_yok",
    nameTr: "Tırnak Yemeyen Koyar",
    emoji: "💅",
    metricType: "daily_boolean",
    unitTr: "gün",
    direction: "higher",
    descriptionTr: "Her gün tırnak yemediğini işaretliyorsun, başta ve sonda da el fotoğrafı atıyorsun. Sondaki fotoğrafta tırnaklar daha çok yenmişse arkadaşlar itiraz eder.",
    descriptionPoliteTr: "Her gün tırnak yemediğinizi işaretleyin, başlangıçta ve bitişte el fotoğrafı paylaşın. En çok temiz gün toplayan kazanır.",
    howMeasuredTr: "Her gün işaretliyorsun, çelınc başında ve sonunda uygulamanın kamerasından el fotoğrafı çekiyorsun. İki fotoğraf yan yana konuyor, aradaki farkı grup görüyor.",
    defaultDurationDays: 14,
    suggestedRewardTr: "Kaybeden kazanana el kremi ve tırnak makası alır.",
    antiCheatTr: "Hile: başkasının eli, eski fotoğraf, işaretleyip kemirmeye devam etmek. Caydırma: fotoğraf sadece uygulama içi kameradan (galeriden yükleme yok), sunucu zaman damgalı; gün içi arkadaş itirazında 5 dk içinde 'canlı el fotoğrafı' istenir, gelmezse itiraz kabul edilir ve o gün düşer.",
    proofRequired: true,
    category: "kotu_aliskanlik",
    maxPerEntry: 1,
    maxPerDay: 1,
  },
  {
    key: "soguk_dus",
    nameTr: "Soğuk Duş Kahramanı",
    emoji: "🥶",
    metricType: "daily_boolean",
    unitTr: "gün",
    direction: "higher",
    descriptionTr: "Her sabah en az bir dakika soğuk su, bağırmak serbest. Her gün işaretliyorsun, en çok gün toplayan kazanır.",
    descriptionPoliteTr: "Her gün en az bir dakika soğuk duş alın ve işaretleyin. En çok gün toplayan kazanır.",
    howMeasuredTr: "Her gün aldım ya da almadım diye işaretliyorsun. İstersen ıslak saç selfie'si veya kısa bir video ekleyebilirsin, grup bunu zorunlu da yapabilir.",
    defaultDurationDays: 7,
    suggestedRewardTr: "Kaybeden kazanana üstünde KOYDUM yazan bir havlu alır.",
    antiCheatTr: "Hile: ılık suyla video çekmek, işaretleyip duş almamak. Caydırma: video/selfie uygulama içi kameradan, sunucu zaman damgalı; arkadaşlar 'buhar var, sıcak su bu' itirazı açar; itiraz kabul edilirse gün düşer. Video zorunlu modunda videosuz gün 'almadı' sayılır.",
    proofRequired: false,
    category: "diger",
    maxPerEntry: 1,
    maxPerDay: 1,
  },
  {
    key: "yatak_toplama",
    nameTr: "Yatak Toplama Sabahı",
    emoji: "🛌",
    metricType: "checkin_deadline",
    unitTr: "gün",
    direction: "higher",
    descriptionTr: "Her sabah dokuzdan önce yatağını toplayıp fotoğrafını atıyorsun. Buruşuk çarşaf sayılmıyor, en çok düzenli sabah toplayan kazanır.",
    descriptionPoliteTr: "Her sabah belirlenen saatten önce yatağınızı toplayıp fotoğrafla check-in yapın. En çok başarılı sabah toplayan kazanır.",
    howMeasuredTr: "Sabah check-in'inde uygulamanın kamerasından toplanmış yatağın fotoğrafını çekiyorsun, galeriden yükleme yok. Geç kalan veya fotoğrafsız check-in sayılmıyor.",
    defaultDurationDays: 7,
    defaultDeadlineTime: "09:00",
    suggestedRewardTr: "Kaybeden kazananın evinde bir kere yatağı toplar.",
    antiCheatTr: "Hile: dünkü fotoğraf, hiç uyunmamış yatak, gece yarısı toplayıp check-in. Caydırma: fotoğraf sadece uygulama içi kameradan (galeriden yükleme yok), sunucu zaman damgası ekler; en erken 05:00; birebir aynı fotoğrafın tekrarı hash ile yakalanır; arkadaşlar 'aynı fotoğraf' itirazı açar, kabul edilirse gün düşer.",
    proofRequired: true,
    category: "diger",
    maxPerEntry: 1,
    maxPerDay: 1,
  },
] as const;

const BY_KEY: Record<string, ChallengeType> = Object.fromEntries(
  CHALLENGE_TYPES.map((type) => [type.key, type])
);

export function getChallengeType(key: string): ChallengeType | undefined {
  return BY_KEY[key];
}

/** Throws when the key is unknown — used on paths where the key came from the DB. */
export function requireChallengeType(key: string): ChallengeType {
  const type = BY_KEY[key];
  if (!type) throw new Error(`Unknown challenge type: ${key}`);
  return type;
}

export function challengeTypesByCategory(): Record<string, ChallengeType[]> {
  const grouped: Record<string, ChallengeType[]> = {};
  for (const type of CHALLENGE_TYPES) {
    (grouped[type.category] ??= []).push(type);
  }
  return grouped;
}

export function challengeTypesForMetric(metricType: MetricType): ChallengeType[] {
  return CHALLENGE_TYPES.filter((type) => type.metricType === metricType);
}

/** Turkish labels for the catalog categories, in display order. */
export const CATEGORY_LABELS_TR: Record<string, string> = {
  hareket: 'Hareket',
  ekran: 'Ekran',
  uyku: 'Uyku',
  beslenme: 'Beslenme',
  zihin: 'Zihin',
  kotu_aliskanlik: 'Kötü Alışkanlık',
  diger: 'Diğer',
};

export const CATEGORY_ORDER = [
  'hareket',
  'ekran',
  'uyku',
  'beslenme',
  'zihin',
  'kotu_aliskanlik',
  'diger',
] as const;
