/**
 * The challenge catalog: every measurable "çelınc" the app offers.
 *
 * Generated from the product design pass and reviewed by hand. Each entry has
 * to be measurable on a phone — see `howMeasuredTr` — and carries anti-abuse
 * caps used by the server when validating entries.
 */
import type { ChallengeType, MetricType } from './types';

export const CHALLENGE_TYPES: readonly ChallengeType[] = [
  {
    key: "adim_yarisi",
    nameTr: "Adım Yarışı",
    emoji: "🚶",
    metricType: "auto_steps",
    unitTr: "adım",
    direction: "higher",
    descriptionTr: "Telefon cebinde, ayaklar yerde. Süre bitince en çok adım atan koyar, en az atan kaz gibi yürümüş sayılır lan. Kanepede gün geçiren rezil olur.",
    descriptionPoliteTr: "Belirlenen süre boyunca en çok adım atan kazanır. Kanepe takımı sonda kalır; üzülmeyin, yürüyün.",
    howMeasuredTr: "Telefonun kendi adım sayacı. iOS: CoreMotion (CMPedometer) son 7 günün adım geçmişini verir; uygulama her açıldığında çelınc başlangıcından itibaren günlük ve saatlik toplamları sorgulayıp sunucuya yazar. Arka plan servisi gerekmez ama kullanıcı en az 7 günde bir (tercihen her gün) uygulamayı açmalı. Android: sürekli arka plan sayımı yok; günlük adım geçmişi Health Connect üzerinden okunur (Samsung Health / Google Fit / Fitbit gibi bir kaynak uygulamanın Health Connect'e yazıyor olması gerekir). Her iki platformda dev build şart, Expo Go'da çalışmaz. Çelınc başlangıç saatinden itibaren sayılır, sunucu günlük toplamı tutar.",
    defaultDurationDays: 3,
    suggestedRewardTr: "Kaybeden herkese döner ısmarlar.",
    antiCheatTr: "Hile: telefonu çamaşır makinesine bantlamak, köpeğin tasmasına takmak, elle sallamak. Caydırma: saatlik adım dağılımı sunucuda tutulur; 1 saatte 12.000+ adım gibi imkânsız sıçramalar 'şüpheli' bayrağı alır (hızlı koşucu bile saatte 10 bin civarı atar) ve arkadaşlar itiraz açabilir. İtiraz kazanırsa o günün adımı silinir. Sadece tek cihaz bağlanabilir; çelınc sırasında cihaz değişirse önceki günler kilitlenir.",
    proofRequired: false,
    category: "hareket",
    maxPerEntry: 100000,
    maxPerDay: 100000,
  },
  {
    key: "kosu_km",
    nameTr: "Koşu Kilometresi",
    emoji: "🏃",
    metricType: "manual_count",
    unitTr: "km",
    direction: "higher",
    descriptionTr: "Haftanın sonunda kim en çok km koşmuşsa o koyar. Yürüyüş sayılmaz, tramvay hiç sayılmaz. Nefesin kesilmediyse koşmamışsındır kanka.",
    descriptionPoliteTr: "Süre boyunca en çok kilometre koşan kazanır. Koşu uygulamasından bir ekran görüntüsü yeter.",
    howMeasuredTr: "Kullanıcı her koşudan sonra km girer (ondalık serbest, ör. 5,2) ve koşu uygulamasından (Strava, Nike Run, Apple Fitness, Google Fit) rota + mesafe + tempo ekran görüntüsü yükler. Sunucu girişleri toplar; ekran görüntüsüz giriş kabul edilmez.",
    defaultDurationDays: 7,
    suggestedRewardTr: "Kaybeden, kazananın bir sonraki koşu ayakkabısına 200 TL katkı yapar (bütçeye göre bir kahve de olur).",
    antiCheatTr: "Hile: bisikletle koşu kaydı, eski koşunun ekran görüntüsü, arabayla 'koşmak'. Caydırma: fotoğraf kanıtı zorunlu, ekran görüntüsünde tarih ve tempo görünmeli; 2:30 dk/km altındaki tempo otomatik şüpheli işaretlenir; günde 42 km üstü şüpheli. Arkadaşlar itiraz eder, çoğunluk 'hile' derse giriş silinir ve o gün 0 sayılır.",
    proofRequired: true,
    category: "hareket",
    maxPerEntry: 60,
    maxPerDay: 100,
  },
  {
    key: "sinav_sayisi",
    nameTr: "Şınav Kapışması",
    emoji: "💪",
    metricType: "manual_count",
    unitTr: "tekrar",
    direction: "higher",
    descriptionTr: "Her gün kaç şınav çektiysen gir. Sonunda toplamı büyük olan koyar. Dizden şınav çekip 'ben yaptım' diyen anında yedi bilsin.",
    descriptionPoliteTr: "Günlük şınav sayınızı girin; süre sonunda toplamı en yüksek olan kazanır. Kısa bir video kanıt istenebilir.",
    howMeasuredTr: "Kullanıcı gün içinde set set girer (ör. 3 set × 20), uygulama günlük toplamı tutar. Günde en az bir set için uygulama içi kameradan 10-30 saniyelik video zorunlu; videolu set 'doğrulanmış' rozeti alır, videosuz setler arkadaş itirazına açıktır. Günlük tavan 300 tekrar.",
    defaultDurationDays: 7,
    suggestedRewardTr: "Kaybeden, kazananın seçtiği rezil profil fotoğrafını 1 gün kullanır.",
    antiCheatTr: "Hile: hava sayısı girmek, yarım şınav, hızlandırılmış video. Caydırma: kanıt videosu zorunlu; sunucu video süresini o setin beyan edilen sayısıyla karşılaştırır (saniyede 1,5 şınavdan fazlası şüpheli: 12 saniyelik videoda 40 şınav olmaz). Arkadaşlar 'form bozuk' itirazı açabilir; itiraz kabul edilirse set yarıya indirilir.",
    proofRequired: true,
    category: "hareket",
    maxPerEntry: 150,
    maxPerDay: 300,
  },
  {
    key: "merdiven_kati",
    nameTr: "Merdiven Canavarı",
    emoji: "🪜",
    metricType: "manual_count",
    unitTr: "kat",
    direction: "higher",
    descriptionTr: "Asansör düşmandır. Çıktığın her kat sayılır. Süre sonunda en çok kat tırmanan koyar; asansör düğmesine basanın bacakları utansın lan.",
    descriptionPoliteTr: "Asansör yerine merdiven kullanın, çıktığınız katları girin. En çok kat tırmanan kazanır.",
    howMeasuredTr: "Kullanıcı çıktığı kat sayısını elle girer (inmek sayılmaz). Otomatik kat sayımı yoktur: iOS'ta CoreMotion 'çıkılan kat' verisi olsa da Expo'nun Pedometer modülü bunu vermez, Android'de standart bir kat verisi yoktur; bu yüzden beyan esaslıdır. Günlük tavan 60 kat. İsteğe bağlı merdiven boşluğu selfie'si (uygulama içi kamera); grup 'fotoğraf zorunlu' modunu açabilir.",
    defaultDurationDays: 5,
    suggestedRewardTr: "Kaybedenler kazananın alışveriş poşetlerini bir kere merdivenden taşır.",
    antiCheatTr: "Hile: aşağı inerken sayı yazmak, yürüyen merdiven, hava sayısı. Caydırma: günlük 60 kat tavanı; tek girişte 20 kat üstü 'şüpheli' işaretlenir ve fotoğraf ister; arkadaşlar itiraz edebilir, çoğunluk hile derse gün sıfırlanır.",
    proofRequired: false,
    category: "hareket",
    maxPerEntry: 30,
    maxPerDay: 60,
  },
  {
    key: "odak_seansi",
    nameTr: "Odak Seansı",
    emoji: "🎯",
    metricType: "focus_minutes",
    unitTr: "dk",
    direction: "higher",
    descriptionTr: "Uygulamayı aç, seansı başlat, telefonu bırak. Kaçıp Instagram'a girersen seans patlar, süre yanar. En çok dakika biriktiren koyar, parmakları kaşınan yedi.",
    descriptionPoliteTr: "Uygulama içi odak sayacını başlatın ve telefona dokunmayın. Uygulamadan çıkarsanız seans bozulur. En çok odak dakikası toplayan kazanır.",
    howMeasuredTr: "Uygulama içi sayaç. Kullanıcı 10 dk - 3 saat arası hedef süre seçer; ekran açık kalır (keep-awake, karartılmış sayaç ekranı). AppState ile izlenir: uygulama arka plana atılır, başka uygulamaya geçilir veya telefon kilitlenirse 15 saniyelik toleranstan sonra seans bozulur ve o seansın süresi sayılmaz (kısa arama/bildirim toleransı). Seans başlangıç/bitişi sunucuya yazılır; günlük tavan 6 saat.",
    defaultDurationDays: 7,
    suggestedRewardTr: "Kaybedenler kazananın seçtiği filmi hep beraber izler, itiraz hakkı yok.",
    antiCheatTr: "Hile: ikinci telefondan scroll'lamak, seansı açıp uyumak veya telefonu bırakıp gitmek. Caydırma: seans sırasında rastgele aralıklarla (20-40 dk) ekranda 'Buradayım' butonu çıkar, 60 sn içinde basılmazsa seans o anda biter ve sadece o ana kadarki süre sayılır; günlük 6 saat tavanı; ikinci telefonun teknik tespiti yok, arkadaşlar 'o saatte bizimle mesajlaşıyordu' itirazını ekran görüntüsüyle açar, çoğunluk hile derse seans silinir.",
    proofRequired: false,
    category: "ekran",
    maxPerEntry: 180,
    maxPerDay: 360,
  },
  {
    key: "ekran_suresi_beyani",
    nameTr: "Ekran Süresi Düellosu",
    emoji: "📱",
    metricType: "manual_lower_is_better",
    unitTr: "dk",
    direction: "lower",
    descriptionTr: "Her gece telefonun ekran süresi raporunu gir, ekran görüntüsünü at. Süre sonunda ortalaması EN DÜŞÜK olan koyar. Günde 8 saat TikTok'ta olan kanka, çok fena yedin.",
    descriptionPoliteTr: "Her gün cihazınızın Ekran Süresi / Dijital Denge raporundaki toplam dakikayı girin ve ekran görüntüsünü ekleyin. En düşük ortalama kazanır.",
    howMeasuredTr: "Kullanıcı gün sonunda (veya ertesi sabah, önceki gün için) iOS Ekran Süresi ya da Android Dijital Denge / Ekran Süresi ekranındaki günlük toplamı dakika olarak girer; ekran görüntüsü zorunludur. Uygulama ekran süresini otomatik okuyamaz (iOS'ta API yok, Android UsageStats izni Play politikalarıyla sorunlu), bu yüzden beyan + ekran görüntüsü esastır. Sunucu günlük ortalamayı hesaplar; girilmeyen gün 1440 dk sayılır.",
    defaultDurationDays: 7,
    suggestedRewardTr: "Kaybeden 1 hafta boyunca grupta 'Ekran Kölesi' etiketiyle görünür.",
    antiCheatTr: "Hile: sahte veya eski ekran görüntüsü, ikinci cihazda kullanım, hiç girmemek. Caydırma: ekran görüntüsünde o günün tarihi görünmeli; girilmeyen gün otomatik 1440 dk; arkadaşlar ekran görüntüsünü inceleyip itiraz açar, çoğunluk hile derse o gün 1440 dk yazılır.",
    proofRequired: true,
    category: "ekran",
    maxPerEntry: 1440,
    maxPerDay: 1440,
    missingDayPenalty: 1440,
  },
  {
    key: "sosyal_medya_orucu",
    nameTr: "Sosyal Medya Orucu",
    emoji: "🚫",
    metricType: "daily_boolean",
    unitTr: "gün",
    direction: "higher",
    descriptionTr: "Instagram, TikTok, X, Reels, Shorts... hepsi yasak. Her akşam 'girmedim' de, en çok temiz gün toplayan koyar. Bir kere 'sadece bakacaktım' dedin mi gün gitti, yedin.",
    descriptionPoliteTr: "Belirlenen sosyal medya uygulamalarına hiç girmediğiniz günleri işaretleyin. En çok temiz gün toplayan kazanır.",
    howMeasuredTr: "Her gün 'girmedim / girdim' işaretlenir. Kanıt olarak gün sonunda Ekran Süresi / Dijital Denge uygulama listesinin ekran görüntüsü yüklenir (sosyal uygulamalar 0 dk görünmeli). İşaretlenmeyen veya ekran görüntüsüz gün 'girdi' sayılır.",
    defaultDurationDays: 7,
    suggestedRewardTr: "Kaybeden kazanana bir hafta boyunca her tartışmada 'haklısın abi' der.",
    antiCheatTr: "Hile: tarayıcıdan girmek, ikinci telefon, uygulamayı silip yeniden yüklemek. Caydırma: ekran görüntüsü kanıtı zorunlu, tarayıcı süresi de listede görünür; arkadaşlar bir story izlenmesi veya beğeni görürse ekran görüntüsüyle itiraz açar, itiraz kabul edilirse o gün 'girdi' sayılır.",
    proofRequired: true,
    category: "ekran",
    maxPerEntry: 1,
    maxPerDay: 1,
  },
  {
    key: "erken_kus",
    nameTr: "Erken Kalkan Koyar",
    emoji: "🌅",
    metricType: "checkin_deadline",
    unitTr: "gün",
    direction: "higher",
    descriptionTr: "Her sabah 07:00'den önce uygulamaya girip 'kalktım' diyeceksin. Saat 07:01 mi? Yedin, gün gitti. Süre sonunda en çok sabah yakalayan koyar, yastıkla evli olan rezil olur.",
    descriptionPoliteTr: "Her sabah belirlenen saatten önce uygulamadan 'kalktım' check-in'i yapın. En çok başarılı sabah toplayan kazanır.",
    howMeasuredTr: "Kullanıcı sabah check-in butonuna basar; sunucu, kendi saatiyle 04:00-07:00 penceresinde olup olmadığını doğrular (telefon saati değil). Geç check-in kabul edilmez, 04:00'ten önce yapılan check-in de sayılmaz. İsteğe bağlı uygulama içi kameradan sabah selfie'si.",
    defaultDurationDays: 5,
    defaultDeadlineTime: "07:00",
    suggestedRewardTr: "Kaybeden kazanana bir sabah kahvaltı hazırlar veya getirir.",
    antiCheatTr: "Hile: telefon saatini geri almak, alarmla check-in yapıp yatağa dönmek, hiç yatmadan 'kalktım' demek. Caydırma: sunucu saati esas alınır, cihaz saati önemsiz; en erken 04:00; grup 'selfie zorunlu' modunu açabilir (gün ışığında, uygulama içi kamera); adım verisi olan cihazlarda (iOS CoreMotion / Health Connect) check-in sonrası 60 dk içinde 300 adım yoksa 'şüpheli' işareti. Arkadaşlar 'bu selfie yataktan çekilmiş' itirazı açabilir.",
    proofRequired: false,
    category: "uyku",
    maxPerEntry: 1,
    maxPerDay: 1,
  },
  {
    key: "erken_yat",
    nameTr: "Erken Yatma Sözü",
    emoji: "🌙",
    metricType: "checkin_deadline",
    unitTr: "gün",
    direction: "higher",
    descriptionTr: "23:00'ten önce 'yattım' de ve telefonu bırak. Gece 02:00'de Reels'te takılan kanka, o gece sayılmaz. En çok erken gece toplayan koyar, gece kuşu yedi.",
    descriptionPoliteTr: "Her gece belirlenen saatten önce 'yatıyorum' check-in'i yapın. En çok başarılı gece toplayan kazanır.",
    howMeasuredTr: "Gece check-in'i sunucu saatine göre 20:00-23:00 penceresinde yapılmalı (öğleden sonra 'yattım' demek sayılmaz). Check-in sonrası uygulama 'uyku modu'na girer; 06:00'ya kadar uygulamada aktif kullanım (sunucuya istek) görülürse gece iptal olur. Uygulama başka uygulamaların kullanımını göremez; bu yüzden asıl denetim arkadaş itirazıdır.",
    defaultDurationDays: 7,
    defaultDeadlineTime: "23:00",
    suggestedRewardTr: "Kaybeden kazanana her gece 23:00'te 'iyi geceler, koydun' sesli mesajı atmak zorunda (1 hafta).",
    antiCheatTr: "Hile: check-in yapıp telefonda takılmaya devam etmek. Caydırma: sunucu saati; check-in sonrası gece uygulama kullanılırsa gece iptal; arkadaşlar gece 01:00'de 'çevrimiçi' veya yeni story görürse ekran görüntüsüyle itiraz açar, çoğunluk kabul ederse gece düşer; isteğe bağlı 'kanıt modu': ertesi sabah uyku uygulaması veya Ekran Süresi'nin gece saatleri ekran görüntüsü.",
    proofRequired: false,
    category: "uyku",
    maxPerEntry: 1,
    maxPerDay: 1,
  },
  {
    key: "su_bardak",
    nameTr: "Su Bardağı Yarışı",
    emoji: "💧",
    metricType: "manual_count",
    unitTr: "bardak",
    direction: "higher",
    descriptionTr: "Her içtiğin bardağı gir. Günde 8'i geçemeyen kaktüs gibi kurumuş demektir. Sonunda en çok bardak deviren koyar; çay, kahve sayılmaz lan, su dedik.",
    descriptionPoliteTr: "İçtiğiniz her su bardağını girin. Süre sonunda toplamı en yüksek olan kazanır. Çay ve kahve sayılmaz.",
    howMeasuredTr: "Kullanıcı her bardak için + butonuna basar (1 bardak = 250 ml). Günlük üst sınır 15 bardak. Günde en fazla bir kez, 08:00-22:00 arasında rastgele bir anda sunucu push bildirimiyle 'dolu bardak / boş şişe fotoğrafı' ister (uygulama içi kamera).",
    defaultDurationDays: 7,
    suggestedRewardTr: "Kaybedenler kazanana 5 litrelik su damacanası hediye eder (şaka değil).",
    antiCheatTr: "Hile: içmeden basmak, gece yarısı 15 bardak birden girmek. Caydırma: bardaklar arası minimum 20 dk aralık (sunucu zamanı); günlük 15 bardak tavanı; rastgele fotoğraf isteğine 5 dk içinde cevap gelmezse o gün yarıya iner. Arkadaşlar itiraz edebilir.",
    proofRequired: false,
    category: "beslenme",
    maxPerEntry: 10,
    maxPerDay: 30,
  },
  {
    key: "sekersiz_gun",
    nameTr: "Şekersiz Günler",
    emoji: "🍬",
    metricType: "daily_boolean",
    unitTr: "gün",
    direction: "higher",
    descriptionTr: "Baklava, kola, çikolata, 'bir tane bir şey olmaz' diyen o ses... hepsi yasak. Her akşam 'şeker yemedim' de. En çok temiz gün toplayan koyar, tatlıya yenilen yedi.",
    descriptionPoliteTr: "Her gün şekerli tatlı ve içecek tüketmediğinizi işaretleyin. En çok temiz gün toplayan kazanır.",
    howMeasuredTr: "Her gün 'yemedim / yedim' işaretlenir. Gün sonunda işaretlenmeyen gün 'yedi' sayılır. İsteğe bağlı fotoğraf kanıtı (öğün fotoğrafları, uygulama içi kamera).",
    defaultDurationDays: 7,
    suggestedRewardTr: "Kaybeden herkese tatlı ısmarlar ama kendisi yiyemez.",
    antiCheatTr: "Hile: gizli gizli yemek, 'şekersiz' etiketli ama şekerli şeyler. Caydırma: dürüstlük sistemi + itiraz. Arkadaşlar ellerinde fotoğraf/story varsa (elinde kola ile görüldüyse) itiraz açar; çoğunluk 'yedi' derse gün düşer. Sunucu itirazın kanıt fotoğrafını saklar.",
    proofRequired: false,
    category: "beslenme",
    maxPerEntry: 1,
    maxPerDay: 1,
  },
  {
    key: "fast_food_yok",
    nameTr: "Fast Food Boykotu",
    emoji: "🍔",
    metricType: "daily_boolean",
    unitTr: "gün",
    direction: "higher",
    descriptionTr: "Hamburger, pizza, kızarmış patates, gece 3 dürümcüsü... yasak. Her gün 'yemedim' de. Kapıya kurye gelen anında yedi, en çok temiz gün toplayan koyar.",
    descriptionPoliteTr: "Her gün fast food yemediğinizi işaretleyin. En çok temiz gün toplayan kazanır. Ev yemeği yiyenler önde.",
    howMeasuredTr: "Her gün 'yemedim / yedim' işaretlenir; işaretlenmeyen gün 'yedi' sayılır. İsteğe bağlı: gün içindeki ana öğünün fotoğrafı ('fotoğraf zorunlu' modu grup tarafından açılabilir, uygulama içi kamera).",
    defaultDurationDays: 7,
    suggestedRewardTr: "Kaybeden kazanana kendi elleriyle bir ev yemeği yapar (sipariş değil).",
    antiCheatTr: "Hile: yemek sipariş uygulamasından gizlice sipariş vermek. Caydırma: arkadaşlar itiraz açabilir (siparişin fotoğrafı, story, ortak sipariş geçmişi); çoğunluk kararıyla o gün düşer. 'Fotoğraf zorunlu' modunda fotoğraf gelmeyen gün otomatik 'yedi' sayılır.",
    proofRequired: false,
    category: "beslenme",
    maxPerEntry: 1,
    maxPerDay: 1,
  },
  {
    key: "sebze_meyve_porsiyon",
    nameTr: "Yeşillik Kotası",
    emoji: "🥦",
    metricType: "manual_count",
    unitTr: "porsiyon",
    direction: "higher",
    descriptionTr: "Günde kaç porsiyon sebze/meyve yedin, gir. Dönerin üstündeki 3 yaprak marul porsiyon değil lan. En çok yeşillik deviren koyar, ketçabı sebze sayan yedi.",
    descriptionPoliteTr: "Yediğiniz sebze ve meyve porsiyonlarını girin. Süre sonunda toplamı en yüksek olan kazanır. Tabak fotoğrafı işleri kolaylaştırır.",
    howMeasuredTr: "Kullanıcı her porsiyon için +1 girer (1 porsiyon = bir avuç / bir orta boy meyve / bir kase salata). Günlük tavan 10 porsiyon. Her porsiyon için uygulama içi kameradan tabak fotoğrafı istenir; sunucu zaman damgası ekler.",
    defaultDurationDays: 7,
    suggestedRewardTr: "Kaybeden kazanana bir meyve sepeti alır veya bir hafta pazar poşetlerini taşır.",
    antiCheatTr: "Hile: aynı tabağı 3 kez fotoğraflamak, internetten fotoğraf indirmek. Caydırma: fotoğraf sadece uygulama içi kameradan (galeriden yükleme yok), sunucu zaman damgası ekler; birebir aynı görüntünün tekrarı hash ile yakalanır, benzer fotoğraflar için arkadaş itirazı; çoğunluk hile derse porsiyon silinir.",
    proofRequired: true,
    category: "beslenme",
    maxPerEntry: 8,
    maxPerDay: 15,
  },
  {
    key: "kitap_sayfa",
    nameTr: "Sayfa Avcısı",
    emoji: "📚",
    metricType: "manual_count",
    unitTr: "sayfa",
    direction: "higher",
    descriptionTr: "Okuduğun her sayfayı gir. Süre sonunda en çok sayfa deviren koyar. Instagram caption'ı okumak sayfa sayılmaz kanka, kitap dedik kitap.",
    descriptionPoliteTr: "Okuduğunuz sayfaları girin; en çok sayfa okuyan kazanır. Basılı kitap veya e-kitap sayılır, kaldığınız sayfanın fotoğrafı yeterli.",
    howMeasuredTr: "Kullanıcı kitabı seçer/oluşturur ve her okuma oturumundan sonra 'kaldığım sayfa' numarasını girer; sunucu önceki değerle farkı alıp okunan sayfayı hesaplar (kitap başına sayfa numarası sadece artabilir). Her girişte kaldığı sayfanın fotoğrafı (uygulama içi kamera) veya e-okuyucu ekran görüntüsü (sayfa/yüzde görünür) zorunlu. Günlük tavan 200 sayfa.",
    defaultDurationDays: 14,
    suggestedRewardTr: "Kaybeden kazanana istediği kitabı alır.",
    antiCheatTr: "Hile: 'bugün 300 sayfa okudum' yazmak, kitabı rastgele açıp fotoğraf çekmek. Caydırma: fotoğraf zorunlu, sayfa numarası kitap başına geriye gidemez; günde 150 sayfa üstü otomatik 'şüpheli' işareti; arkadaşlar 'o bölümde ne oluyor, anlat' itirazı açar, cevap gelmezse veya çoğunluk inanmazsa giriş silinir.",
    proofRequired: true,
    category: "zihin",
    maxPerEntry: 300,
    maxPerDay: 500,
  },
  {
    key: "dil_pratigi",
    nameTr: "Dil Pratiği Dakikası",
    emoji: "🔤",
    metricType: "manual_count",
    unitTr: "dk",
    direction: "higher",
    descriptionTr: "Her gün kaç dakika yabancı dil çalıştın gir, Duolingo ekran görüntüsünü at. En çok dakika biriktiren koyar. Baykuş sana bildirim atarken sen Reels izliyorsan yedin.",
    descriptionPoliteTr: "Her gün yabancı dil çalışma dakikanızı girin ve dil uygulamasından ekran görüntüsü ekleyin. En çok dakika toplayan kazanır.",
    howMeasuredTr: "Kullanıcı günlük çalışma dakikasını girer ve o güne ait ilerlemeyi gösteren ekran görüntüsü ekler (Duolingo/Busuu günlük XP-ders ekranı, Anki 'bugün' istatistiği, ders notu fotoğrafı). Ekran görüntüsü dakikayı değil 'o gün çalışıldığını' kanıtlar; dakika beyan esaslıdır. Günlük tavan 120 dk. Ekran görüntüsü gelmeyen gün 0 sayılır.",
    defaultDurationDays: 14,
    suggestedRewardTr: "Kaybeden kazananın dil uygulaması aboneliğine 1 aylık katkı yapar.",
    antiCheatTr: "Hile: uygulamayı açık bırakıp dakika saymak, eski ekran görüntüsü, 5 dk çalışıp 120 yazmak. Caydırma: ekran görüntüsünde o günün ilerlemesi (XP/ders/seri) görünmeli; günlük 120 dk tavanı; ilerlemeye göre orantısız dakika (10 XP'ye 120 dk gibi) arkadaş itirazına açıktır, çoğunluk hile derse gün yarıya iner.",
    proofRequired: true,
    category: "zihin",
    maxPerEntry: 120,
    maxPerDay: 240,
  },
  {
    key: "gunluk_yazma",
    nameTr: "Günlük Defteri",
    emoji: "📝",
    metricType: "daily_boolean",
    unitTr: "gün",
    direction: "higher",
    descriptionTr: "Her gün en az yarım sayfa günlük yaz, defterin fotoğrafını at. 'Bugün iyiydi' yazıp kapatan kanka, o yarım sayfa değil, o mesaj. En çok yazılı gün toplayan koyar, boş sayfa bırakan yedi.",
    descriptionPoliteTr: "Her gün en az yarım sayfa günlük yazın ve sayfanın fotoğrafını çekin. En çok yazılı gün toplayan kazanır.",
    howMeasuredTr: "Günlük 'yazdım / yazmadım' işareti; uygulama içi kameradan o günün tarihi görünen defter sayfası fotoğrafı zorunlu (dijital günlük tutanlar için not uygulaması ekran görüntüsü kabul). Gizlilik için fotoğraf arkadaşlara düşük çözünürlükte (yazı okunmaz, sayfanın dolu olduğu görünür) gösterilir. İşaretlenmeyen veya fotoğrafsız gün 'yazmadı' sayılır.",
    defaultDurationDays: 14,
    suggestedRewardTr: "Kaybeden kazanana güzel bir defter ve kalem alır.",
    antiCheatTr: "Hile: eski sayfayı fotoğraflamak, iki satır yazıp 'yazdım' demek. Caydırma: fotoğraf sadece uygulama içi kameradan, sunucu zaman damgası ekler, birebir aynı fotoğrafın tekrarı hash ile yakalanır; sayfada tarih görünmeli; arkadaşlar 'sayfa boş' itirazı açabilir, çoğunluk kabul ederse gün düşer.",
    proofRequired: true,
    category: "zihin",
    maxPerEntry: 1,
    maxPerDay: 1,
  },
  {
    key: "sigara_yok",
    nameTr: "Dumansız Günler",
    emoji: "🚭",
    metricType: "daily_boolean",
    unitTr: "gün",
    direction: "higher",
    descriptionTr: "Her gün 'içmedim' de. Bir tane bile çekersen o gün gitti. En çok temiz gün toplayan koyar, 'bir tek' diyen yedi. Bu sefer ciğerin bile sana koyar.",
    descriptionPoliteTr: "Her gün sigara içmediğinizi işaretleyin. En çok temiz gün toplayan kazanır. Zor ama arkadaşlar destek olur.",
    howMeasuredTr: "Her gün 'içmedim / içtim' işaretlenir; işaretlenmeyen gün 'içti' sayılır. Ardışık temiz gün serisi ayrıca gösterilir. İsteğe bağlı 'kanıt modu': her akşam 22:00 check-in + uygulama içi kameradan selfie.",
    defaultDurationDays: 14,
    suggestedRewardTr: "Kaybeden, kazananın bir aylık sigara parasına denk bir hediye alır.",
    antiCheatTr: "Hile: gizli içmek. Caydırma: dürüstlük + arkadaş itirazı (story, birlikte görülme, fotoğraf); çoğunluk 'içti' derse gün düşer. Kanıt modunda 22:00 selfie'si gelmeyen gün 'içti' sayılır. Yalan söyleyen kendi kendine koymuş olur.",
    proofRequired: false,
    category: "kotu_aliskanlik",
    maxPerEntry: 1,
    maxPerDay: 1,
  },
  {
    key: "alkol_yok",
    nameTr: "Ayık Kalma Yarışı",
    emoji: "🍺",
    metricType: "daily_boolean",
    unitTr: "gün",
    direction: "higher",
    descriptionTr: "Her gün 'içmedim' de. Cuma akşamı 'bir bira olsun' diyen kanka, o günü yedi. En çok ayık gün toplayan koyar, sabah baş ağrısıyla uyanan rezil olur.",
    descriptionPoliteTr: "Her gün alkol almadığınızı işaretleyin. En çok temiz gün toplayan kazanır.",
    howMeasuredTr: "Her gün 'içmedim / içtim' işaretlenir; işaretlenmeyen gün 'içti' sayılır. İsteğe bağlı 'kanıt modu': akşam 22:00'de 'ayığım' check-in'i + uygulama içi kameradan selfie.",
    defaultDurationDays: 14,
    suggestedRewardTr: "Kaybeden bir sonraki buluşmada herkese alkolsüz içecekleri ısmarlar.",
    antiCheatTr: "Hile: gizli içmek, işaretlemeyi 'unutmak'. Caydırma: işaretlenmeyen gün otomatik düşer; arkadaşlar story/fotoğraf ile itiraz açar, çoğunluk kararıyla gün düşer. Kanıt modu açıksa 22:00 selfie'si gelmeyen gün 'içti' sayılır.",
    proofRequired: false,
    category: "kotu_aliskanlik",
    maxPerEntry: 1,
    maxPerDay: 1,
  },
  {
    key: "tirnak_yeme_yok",
    nameTr: "Tırnak Yemeyen Koyar",
    emoji: "💅",
    metricType: "daily_boolean",
    unitTr: "gün",
    direction: "higher",
    descriptionTr: "Her gün 'yemedim' de, sonunda tırnak fotoğrafını at. Toplantıda parmağı ağzında yakalanan yedi. En çok temiz günü toplayan koyar, kemirgen takımı rezil olur.",
    descriptionPoliteTr: "Her gün tırnak yemediğinizi işaretleyin, çelınc başında ve sonunda el fotoğrafı paylaşın. En çok temiz gün toplayan kazanır.",
    howMeasuredTr: "Günlük 'yemedim / yedim' işareti; işaretlenmeyen gün 'yedi' sayılır. Çelınc başında ve sonunda uygulama içi kameradan el fotoğrafı zorunlu; iki fotoğraf yan yana gösterilir. Bitiş fotoğrafında tırnaklar başlangıçtan daha yenik görünüyorsa arkadaşlar toplu itiraz açar; çoğunluk 'yemiş' derse son 3 gün düşer.",
    defaultDurationDays: 14,
    suggestedRewardTr: "Kaybeden kazanana manikür veya el kremi seti alır.",
    antiCheatTr: "Hile: başkasının eli, eski fotoğraf, işaretleyip kemirmeye devam etmek. Caydırma: fotoğraf sadece uygulama içi kameradan (galeriden yükleme yok), sunucu zaman damgalı; gün içi arkadaş itirazında 5 dk içinde 'canlı el fotoğrafı' istenir, gelmezse itiraz kabul edilir ve o gün düşer.",
    proofRequired: true,
    category: "kotu_aliskanlik",
    maxPerEntry: 1,
    maxPerDay: 1,
  },
  {
    key: "soguk_dus",
    nameTr: "Soğuk Duş Kahramanı",
    emoji: "🥶",
    metricType: "daily_boolean",
    unitTr: "gün",
    direction: "higher",
    descriptionTr: "Her sabah en az 1 dk soğuk su. Çığlık atman serbest, kaçman yasak. Her gün 'aldım' de, en çok buzlu gün toplayan koyar. Ilık suya kaçan yedi.",
    descriptionPoliteTr: "Her gün en az 1 dakika soğuk duş alın ve işaretleyin. En çok gün toplayan kazanır.",
    howMeasuredTr: "Günlük 'aldım / almadım' işareti; işaretlenmeyen gün 'almadı' sayılır. İsteğe bağlı 15 saniyelik video (musluk + yüz ifadesi) veya ıslak saç selfie'si, uygulama içi kameradan; grup 'video zorunlu' modunu açabilir.",
    defaultDurationDays: 7,
    suggestedRewardTr: "Kaybeden kazanana üstüne 'KOYDUM' yazılı bir havlu aldırır.",
    antiCheatTr: "Hile: ılık suyla video çekmek, işaretleyip duş almamak. Caydırma: video/selfie uygulama içi kameradan, sunucu zaman damgalı; arkadaşlar 'buhar var, sıcak su bu' itirazı açar; itiraz kabul edilirse gün düşer. Video zorunlu modunda videosuz gün 'almadı' sayılır.",
    proofRequired: false,
    category: "diger",
    maxPerEntry: 1,
    maxPerDay: 1,
  },
  {
    key: "yatak_toplama",
    nameTr: "Yatak Toplama Sabahı",
    emoji: "🛌",
    metricType: "checkin_deadline",
    unitTr: "gün",
    direction: "higher",
    descriptionTr: "Her sabah 09:00'dan önce yatağı topla, fotoğrafını at. Buruşuk çarşaf, kalkmamış adam demektir. En çok düzenli sabah toplayan koyar, çarşafı yerde olan yedi.",
    descriptionPoliteTr: "Her sabah belirlenen saatten önce yatağınızı toplayıp fotoğrafla check-in yapın. En çok başarılı sabah toplayan kazanır.",
    howMeasuredTr: "Sabah check-in'i sunucu saatine göre 05:00-09:00 penceresinde yapılmalı ve uygulama içi kameradan çekilmiş toplanmış yatak fotoğrafı içermeli. Fotoğrafsız, geç veya pencere dışı check-in sayılmaz.",
    defaultDurationDays: 7,
    defaultDeadlineTime: "09:00",
    suggestedRewardTr: "Kaybeden kazananın evinde bir kere yatağı toplar veya çarşafı değiştirir.",
    antiCheatTr: "Hile: dünkü fotoğraf, hiç uyunmamış yatak, gece yarısı toplayıp check-in. Caydırma: fotoğraf sadece uygulama içi kameradan (galeriden yükleme yok), sunucu zaman damgası ekler; en erken 05:00; birebir aynı fotoğrafın tekrarı hash ile yakalanır; arkadaşlar 'aynı fotoğraf' itirazı açar, kabul edilirse gün düşer.",
    proofRequired: true,
    category: "diger",
    maxPerEntry: 1,
    maxPerDay: 1,
  },
] as const;

const BY_KEY: Record<string, ChallengeType> = Object.fromEntries(
  CHALLENGE_TYPES.map((type) => [type.key, type])
);

export function getChallengeType(key: string): ChallengeType | undefined {
  return BY_KEY[key];
}

/** Throws when the key is unknown — used on paths where the key came from the DB. */
export function requireChallengeType(key: string): ChallengeType {
  const type = BY_KEY[key];
  if (!type) throw new Error(`Unknown challenge type: ${key}`);
  return type;
}

export function challengeTypesByCategory(): Record<string, ChallengeType[]> {
  const grouped: Record<string, ChallengeType[]> = {};
  for (const type of CHALLENGE_TYPES) {
    (grouped[type.category] ??= []).push(type);
  }
  return grouped;
}

export function challengeTypesForMetric(metricType: MetricType): ChallengeType[] {
  return CHALLENGE_TYPES.filter((type) => type.metricType === metricType);
}

/** Turkish labels for the catalog categories, in display order. */
export const CATEGORY_LABELS_TR: Record<string, string> = {
  hareket: 'Hareket',
  ekran: 'Ekran',
  uyku: 'Uyku',
  beslenme: 'Beslenme',
  zihin: 'Zihin',
  kotu_aliskanlik: 'Kötü Alışkanlık',
  diger: 'Diğer',
};

export const CATEGORY_ORDER = [
  'hareket',
  'ekran',
  'uyku',
  'beslenme',
  'zihin',
  'kotu_aliskanlik',
  'diger',
] as const;
