/**
 * The challenge catalog: every measurable "çelınc" the app offers.
 *
 * Generated from the product design pass and reviewed by hand. Each entry has
 * to be measurable on a phone — see `howMeasuredTr` — and carries anti-abuse
 * caps used by the server when validating entries.
 */
import type { ChallengeType, DeviceMetric, MetricType } from './types';

export const CHALLENGE_TYPES: readonly ChallengeType[] = [
  {
    key: "adim_yarisi",
    nameTr: "Adım Yarışı",
    emoji: "🚶",
    metricType: "auto_steps",
    unitTr: "adım",
    direction: "higher",
    descriptionTr: "Kim daha çok yürüdüyse o kazanır. Telefon cebinde durduğu sürece sayıyor.",
    descriptionPoliteTr: "Süre boyunca en çok adım atan kazanır. Telefonunuzu yanınızda taşımanız yeterli.",
    howMeasuredTr: "iPhone'da telefonun kendi adım sayacından okunuyor, günde bir kere uygulamayı açman yeterli. Android'de Health Connect kuruluysa oradan alınıyor; kurulu değilse adımlar sadece uygulama açıkken sayılır, o günün gerçek sayısını elle de yazabilirsin. Elle yazdığın sayıyla telefonun saydığı sayıdan hangisi yüksekse o kalır. Günde en fazla 100.000 adım yazılır.",
    defaultDurationDays: 3,
    suggestedRewardTr: "Kaybeden herkese döner ısmarlar.",
    antiCheatTr: "Hile: telefonu çamaşır makinesine bantlamak, köpeğin tasmasına takmak, elle sallamak, Android'de hayalî bir sayı yazmak. Caydırma: günde en fazla 100.000 adım yazılır; arkadaşların her günün adımına itiraz açabilir, diğer oyuncuların çoğunluğu itiraz ederse o günün adımı silinir. Gerisini uygulama değil arkadaşların yakalar.",
    proofRequired: false,
    category: "hareket",
    maxPerEntry: 100000,
    maxPerDay: 100000,
    deviceMetric: "steps",
  },
  {
    key: "kosu_km",
    nameTr: "Koşu Kilometresi",
    emoji: "🏃",
    metricType: "manual_count",
    unitTr: "km",
    direction: "higher",
    descriptionTr: "Süre sonunda en çok kilometre koşan kazanır. Yürüyüş koşu değil, ikimiz de biliyoruz.",
    descriptionPoliteTr: "Süre boyunca en çok kilometre koşan kazanır. Fotoğraf kanıtı açıksa koşu uygulamanızdan bir ekran görüntüsü yeterli.",
    howMeasuredTr: "Her koşudan sonra kaç kilometre koştuğunu sen giriyorsun, uygulama günün toplamını tutuyor. Fotoğraf kanıtı açıksa (bu tipte varsayılan açık) girişe koşu uygulamandan bir ekran görüntüsü eklemen gerekiyor, galeriden seçebilirsin. Tek girişte en fazla 60, günde en fazla 100 km yazılır.",
    defaultDurationDays: 7,
    suggestedRewardTr: "Kaybeden, kazananın yeni koşu ayakkabısına 200 lira katkı yapar.",
    antiCheatTr: "Hile: bisikletle koşu kaydı, eski koşunun ekran görüntüsü, arabayla 'koşmak'. Caydırma: tek girişte 60, günde 100 km tavanı; ekran görüntüsünü arkadaşların görür, tarihi ya da temposu tutmuyorsa itiraz açar, diğer oyuncuların çoğunluğu itiraz ederse giriş silinir. İtiraz yiyen girişi kendin de silemezsin.",
    proofRequired: true,
    category: "hareket",
    maxPerEntry: 60,
    maxPerDay: 100,
  },
  {
    key: "sinav_sayisi",
    nameTr: "Şınav Kapışması",
    emoji: "💪",
    metricType: "manual_count",
    unitTr: "tekrar",
    direction: "higher",
    descriptionTr: "Her gün kaç şınav çektiysen giriyorsun, toplamı en yüksek olan kazanır. Dizden çekilen şınav sayılmıyor.",
    descriptionPoliteTr: "Günlük şınav sayınızı girin, süre sonunda toplamı en yüksek olan kazanır. Fotoğraf kanıtı açıksa her girişe bir fotoğraf eklersiniz.",
    howMeasuredTr: "Setleri sen giriyorsun, uygulama günlük toplamı tutuyor. Fotoğraf kanıtı açıksa (bu tipte varsayılan açık) her sete bir fotoğraf ekliyorsun, kameradan ya da galeriden. Tek sette en fazla 150, günde en fazla 300 tekrar yazılır.",
    defaultDurationDays: 7,
    suggestedRewardTr: "Kaybeden bir gün boyunca kazananın seçtiği profil fotoğrafını kullanır.",
    antiCheatTr: "Hile: hava sayısı girmek, yarım şınav. Caydırma: tek sette 150, günde 300 tekrar tavanı; sayıyı ve fotoğrafı arkadaşların görür, inanmayan itiraz açar, diğer oyuncuların çoğunluğu itiraz ederse set silinir.",
    proofRequired: true,
    category: "hareket",
    maxPerEntry: 150,
    maxPerDay: 300,
  },
  {
    key: "merdiven_kati",
    nameTr: "Merdiven Canavarı",
    emoji: "🪜",
    metricType: "manual_count",
    unitTr: "kat",
    direction: "higher",
    descriptionTr: "Asansöre binmek yok. Çıktığın her kat sayılıyor, en çok tırmanan kazanır.",
    descriptionPoliteTr: "Asansör yerine merdiven kullanın ve çıktığınız katları girin. En çok kat tırmanan kazanır.",
    howMeasuredTr: "Çıktığın kat sayısını sen giriyorsun, inmek sayılmıyor; uygulama günün toplamını tutuyor. Telefon bunu kendi başına ölçemiyor, çelıncı kuran fotoğraf kanıtını açarsa her girişe fotoğraf eklemen gerekiyor. Tek girişte en fazla 30, günde en fazla 60 kat yazılır.",
    defaultDurationDays: 5,
    suggestedRewardTr: "Kaybedenler kazananın alışveriş poşetlerini bir kere yukarı taşır.",
    antiCheatTr: "Hile: aşağı inerken sayı yazmak, yürüyen merdiven, hava sayısı. Caydırma: tek girişte 30, günde 60 kat tavanı; arkadaşların itiraz edebilir, diğer oyuncuların çoğunluğu itiraz ederse giriş silinir.",
    proofRequired: false,
    category: "hareket",
    maxPerEntry: 30,
    maxPerDay: 60,
  },
  {
    key: "odak_seansi",
    nameTr: "Odak Seansı",
    emoji: "🎯",
    metricType: "focus_minutes",
    unitTr: "dk",
    direction: "higher",
    descriptionTr: "Sayacı başlatıp telefonu bırakıyorsun. Instagram'a bakmak için çıkarsan seans yanar, en çok dakika biriktiren kazanır.",
    descriptionPoliteTr: "Uygulamadaki odak sayacını başlatın ve telefona dokunmayın. En çok odak dakikası toplayan kazanır.",
    howMeasuredTr: "Süreyi uygulamanın kendi sayacı tutuyor. Başka bir uygulamaya geçer ya da telefonu kilitlersen 10 saniye içinde dönmen lazım, yoksa seans yanar. Yanan seansın o ana kadar dolan tam dakikalarını yine de kaydedebilirsin, yarım kalan dakika gider.",
    defaultDurationDays: 7,
    suggestedRewardTr: "Kaybedenler kazananın seçtiği filmi hep beraber izler.",
    antiCheatTr: "Hile: ikinci telefondan scroll'lamak, seansı açıp uyumak veya telefonu bırakıp gitmek. Caydırma: uygulamadan 10 saniyeden uzun çıkarsan seans yanar; bir seans en fazla 180, bir gün en fazla 360 dakika; ikinci telefonun teknik tespiti yok, arkadaşların 'o saatte bizimle mesajlaşıyordu' diye itiraz açar, diğer oyuncuların çoğunluğu itiraz ederse seans silinir.",
    proofRequired: false,
    category: "ekran",
    maxPerEntry: 180,
    maxPerDay: 360,
  },
  {
    key: "ekran_suresi_beyani",
    nameTr: "Ekran Süresi Düellosu",
    emoji: "📱",
    metricType: "manual_lower_is_better",
    unitTr: "dk",
    direction: "lower",
    descriptionTr: "Günlük ekran süresi ortalaması en düşük olan kazanır. Android'de telefon kendi sayıyor, iPhone'da her gece ekran görüntüsüyle giriyorsun. Günde sekiz saat TikTok izleyen baştan kaybetmiş.",
    descriptionPoliteTr: "Süre boyunca günlük ekran süresi ortalaması en düşük olan kazanır. Android telefonlar değeri kendisi okur; iPhone'da Ekran Süresi raporundaki toplamı ekran görüntüsüyle girersiniz.",
    howMeasuredTr: "Android'de telefonun kendi kullanım verisinden okunuyor: bir kere 'kullanım erişimi' izni veriyorsun, gerisi otomatik, elle giriş kapanıyor. iPhone'da Apple bu veriyi hiçbir uygulamaya açmıyor, orada Ekran Süresi ekranındaki toplamı ekran görüntüsüyle sen giriyorsun. Girmediğin gün 1440 dakika yazılıyor.",
    defaultDurationDays: 7,
    suggestedRewardTr: "Kaybeden bir hafta boyunca grupta 'Ekran Kölesi' olarak görünür.",
    antiCheatTr: "Hile: sahte veya eski ekran görüntüsü, ikinci cihazda kullanım, hiç girmemek. Caydırma: Android'de değer telefondan okunur ve elle değiştirilemez; iPhone'da ekran görüntüsünde o günün tarihi görünmeli; girilmeyen gün otomatik 1440 dk; arkadaşlar ekran görüntüsünü inceleyip itiraz açar, çoğunluk hile derse o gün 1440 dk yazılır.",
    proofRequired: true,
    category: "ekran",
    maxPerEntry: 1440,
    maxPerDay: 1440,
    missingDayPenalty: 1440,
    deviceMetric: "screen_time",
  },
  {
    key: "sosyal_medya_orucu",
    nameTr: "Sosyal Medya Orucu",
    emoji: "🚫",
    metricType: "daily_boolean",
    unitTr: "gün",
    direction: "higher",
    descriptionTr: "Instagram, TikTok, X, hiçbiri yok. Her akşam girmediğini işaretliyorsun.",
    descriptionPoliteTr: "Belirlenen sosyal medya uygulamalarına girmediğiniz günleri işaretleyin. En çok temiz gün toplayan kazanır.",
    howMeasuredTr: "Her gün 'Yaptım' ya da 'Yapmadım' diye işaretliyorsun, dünü unuttuysan onu da sonradan işaretleyebilirsin. Fotoğraf falan yok, işaretlemediğin gün temiz gün sayılmıyor.",
    defaultDurationDays: 7,
    suggestedRewardTr: "Kaybeden bir hafta boyunca kazananın her dediğine 'haklısın abi' der.",
    antiCheatTr: "Hile: tarayıcıdan girmek, ikinci telefon, uygulamayı silip yeniden yüklemek. Caydırma: uygulama telefonunun içini göremiyor, iş dürüstlüğe ve arkadaşlara kalıyor; biri story izlediğini ya da beğeni attığını görürse itiraz açar, diğer oyuncuların çoğunluğu itiraz ederse o gün düşer.",
    proofRequired: false,
    category: "ekran",
    maxPerEntry: 1,
    maxPerDay: 1,
  },
  {
    key: "erken_kus",
    nameTr: "Erken Kalkan Koyar",
    emoji: "🌅",
    metricType: "checkin_deadline",
    unitTr: "gün",
    direction: "higher",
    descriptionTr: "Her sabah yediden önce uygulamayı açıp 'Geldim' diyeceksin. Bir dakika geç kalsan o gün gitti, en çok sabah yakalayan kazanır.",
    descriptionPoliteTr: "Her sabah belirlenen saatten önce uygulamadan 'Geldim' check-in'i yapın. En çok başarılı sabah toplayan kazanır.",
    howMeasuredTr: "Sabah 'Geldim' butonuna basıyorsun, günde bir kere. Saate telefonun değil sunucu bakıyor, senin saat diliminde; telefonun saatiyle oynamak işe yaramıyor. 04:00'ten önce basılan check-in kabul edilmiyor, saatinden sonra basılan da o gün için sıfır.",
    defaultDurationDays: 5,
    defaultDeadlineTime: "07:00",
    checkinWindowStart: "04:00",
    suggestedRewardTr: "Kaybeden kazanana bir sabah kahvaltı getirir.",
    antiCheatTr: "Hile: telefon saatini geri almak, alarmla check-in yapıp yatağa dönmek. Caydırma: sunucu saati esas alınır, cihaz saati önemsiz; en erken 04:00, günde tek check-in; sonrasında ne yaptığını uygulama göremiyor, arkadaşların 'basıp yattı' diye itiraz açar, diğer oyuncuların çoğunluğu itiraz ederse gün düşer.",
    proofRequired: false,
    category: "uyku",
    maxPerEntry: 1,
    maxPerDay: 1,
  },
  {
    key: "erken_yat",
    nameTr: "Erken Yatma Sözü",
    emoji: "🌙",
    metricType: "checkin_deadline",
    unitTr: "gün",
    direction: "higher",
    descriptionTr: "23:00'ten önce 'Geldim' deyip telefonu bırakacaksın. Sonra Reels'e dalarsan uygulama görmüyor ama arkadaşların görür, en çok erken gece toplayan kazanır.",
    descriptionPoliteTr: "Her gece belirlenen saatten önce uygulamadan check-in yapın. En çok başarılı gece toplayan kazanır.",
    howMeasuredTr: "Akşam 'Geldim' butonuna basıyorsun, günde bir kere; saate sunucu bakıyor, senin saat diliminde. 19:00'dan önce basamıyorsun, saatinden sonra basarsan o gece sıfır. Check-in'den sonra telefonda ne yaptığını uygulama göremiyor.",
    defaultDurationDays: 7,
    defaultDeadlineTime: "23:00",
    checkinWindowStart: "19:00",
    suggestedRewardTr: "Kaybeden bir hafta boyunca her gece 23:00'te kazanana iyi geceler mesajı atar.",
    antiCheatTr: "Hile: check-in yapıp telefonda takılmaya devam etmek. Caydırma: sunucu saati, günde tek check-in, en erken 19:00; sonrasını uygulama göremiyor, arkadaşların gece 01:00'de seni çevrimiçi ya da yeni story'de görürse itiraz açar, diğer oyuncuların çoğunluğu itiraz ederse gece düşer.",
    proofRequired: false,
    category: "uyku",
    maxPerEntry: 1,
    maxPerDay: 1,
  },
  {
    key: "su_bardak",
    nameTr: "Su Bardağı Yarışı",
    emoji: "💧",
    metricType: "manual_count",
    unitTr: "bardak",
    direction: "higher",
    descriptionTr: "İçtiğin her bardağı giriyorsun, sonunda toplamı en yüksek olan kazanır. Çay kahve sayılmıyor, su dedik.",
    descriptionPoliteTr: "İçtiğiniz her su bardağını girin, toplamı en yüksek olan kazanır. Çay ve kahve sayılmaz.",
    howMeasuredTr: "Her bardak için +1'e basıyorsun ya da sayıyı yazıyorsun, bir bardak 250 ml sayılıyor; uygulama günün toplamını tutuyor. Tek girişte en fazla 10, günde en fazla 30 bardak yazılır. Çelıncı kuran fotoğraf kanıtını açarsa her girişe fotoğraf eklemen gerekiyor.",
    defaultDurationDays: 7,
    suggestedRewardTr: "Kaybedenler kazanana bir damacana su alır.",
    antiCheatTr: "Hile: içmeden basmak, gece yarısı 15 bardak birden girmek. Caydırma: tek girişte 10, günde 30 bardak tavanı; arkadaşların itiraz edebilir, diğer oyuncuların çoğunluğu itiraz ederse giriş silinir. Gerisi dürüstlük.",
    proofRequired: false,
    category: "beslenme",
    maxPerEntry: 10,
    maxPerDay: 30,
  },
  {
    key: "sekersiz_gun",
    nameTr: "Şekersiz Günler",
    emoji: "🍬",
    metricType: "daily_boolean",
    unitTr: "gün",
    direction: "higher",
    descriptionTr: "Tatlı yok, kola yok. Her akşam şeker yemediğini işaretliyorsun.",
    descriptionPoliteTr: "Her gün şekerli yiyecek ve içecek tüketmediğinizi işaretleyin. En çok temiz gün toplayan kazanır.",
    howMeasuredTr: "Her gün 'Yaptım' ya da 'Yapmadım' diye işaretliyorsun, dünü de sonradan işaretleyebilirsin. İşaretlemediğin gün temiz gün sayılmıyor. Fotoğraf adımı yok, iş dürüstlüğe ve arkadaşlara kalıyor.",
    defaultDurationDays: 7,
    suggestedRewardTr: "Kaybeden herkese tatlı ısmarlar ama kendisi yemez.",
    antiCheatTr: "Hile: gizli gizli yemek, 'şekersiz' etiketli ama şekerli şeyler. Caydırma: dürüstlük ve itiraz. Elinde kolayla görülürsen arkadaşların itiraz açar, diğer oyuncuların çoğunluğu itiraz ederse gün düşer.",
    proofRequired: false,
    category: "beslenme",
    maxPerEntry: 1,
    maxPerDay: 1,
  },
  {
    key: "fast_food_yok",
    nameTr: "Fast Food Boykotu",
    emoji: "🍔",
    metricType: "daily_boolean",
    unitTr: "gün",
    direction: "higher",
    descriptionTr: "Hamburger, pizza, gece dürümü yok. En çok temiz gün toplayan kazanır, kapıya kurye gelen o günü kaybeder.",
    descriptionPoliteTr: "Her gün fast food yemediğinizi işaretleyin. En çok temiz gün toplayan kazanır.",
    howMeasuredTr: "Her gün 'Yaptım' ya da 'Yapmadım' diye işaretliyorsun, dünü de sonradan işaretleyebilirsin. İşaretlemediğin gün temiz gün sayılmıyor, fotoğraf adımı yok.",
    defaultDurationDays: 7,
    suggestedRewardTr: "Kaybeden kazanana kendi eliyle bir ev yemeği yapar.",
    antiCheatTr: "Hile: yemek sipariş uygulamasından gizlice sipariş vermek. Caydırma: arkadaşların story'de ya da masada kutuyu görürse itiraz açar, diğer oyuncuların çoğunluğu itiraz ederse o gün düşer.",
    proofRequired: false,
    category: "beslenme",
    maxPerEntry: 1,
    maxPerDay: 1,
  },
  {
    key: "sebze_meyve_porsiyon",
    nameTr: "Yeşillik Kotası",
    emoji: "🥦",
    metricType: "manual_count",
    unitTr: "porsiyon",
    direction: "higher",
    descriptionTr: "Yediğin sebze ve meyve porsiyonlarını giriyorsun, en çok toplayan kazanır. Dönerin içindeki marul porsiyon değil.",
    descriptionPoliteTr: "Yediğiniz sebze ve meyve porsiyonlarını girin. Süre sonunda toplamı en yüksek olan kazanır.",
    howMeasuredTr: "Her porsiyon için +1'e basıyorsun ya da sayıyı yazıyorsun, bir porsiyon bir avuç ya da bir orta boy meyve demek. Fotoğraf kanıtı açıksa (bu tipte varsayılan açık) her girişe tabak fotoğrafı ekliyorsun, kameradan ya da galeriden. Tek girişte en fazla 8, günde en fazla 15 porsiyon yazılır.",
    defaultDurationDays: 7,
    suggestedRewardTr: "Kaybeden kazanana bir meyve sepeti alır.",
    antiCheatTr: "Hile: aynı tabağı 3 kez fotoğraflamak, internetten fotoğraf indirmek. Caydırma: tek girişte 8, günde 15 porsiyon tavanı; fotoğrafları arkadaşların görür, aynı tabak ikinci kez gelirse itiraz açar, diğer oyuncuların çoğunluğu itiraz ederse porsiyon silinir.",
    proofRequired: true,
    category: "beslenme",
    maxPerEntry: 8,
    maxPerDay: 15,
  },
  {
    key: "kitap_sayfa",
    nameTr: "Sayfa Avcısı",
    emoji: "📚",
    metricType: "manual_count",
    unitTr: "sayfa",
    direction: "higher",
    descriptionTr: "Okuduğun sayfaları giriyorsun, süre sonunda en çok sayfa deviren kazanır. Story okumak sayfa sayılmıyor kanka.",
    descriptionPoliteTr: "Okuduğunuz sayfaları girin, en çok sayfa okuyan kazanır. Basılı kitap da e-kitap da olur.",
    howMeasuredTr: "Her okumadan sonra kaç sayfa okuduğunu sen giriyorsun, uygulama toplamı tutuyor. Fotoğraf kanıtı açıksa (bu tipte varsayılan açık) girişe kaldığın sayfanın fotoğrafını ekliyorsun, kameradan ya da galeriden. Tek girişte en fazla 300, günde en fazla 500 sayfa yazılır.",
    defaultDurationDays: 14,
    suggestedRewardTr: "Kaybeden kazanana istediği kitabı alır.",
    antiCheatTr: "Hile: 'bugün 300 sayfa okudum' yazmak, kitabı rastgele açıp fotoğraf çekmek. Caydırma: tek girişte 300, günde 500 sayfa tavanı; arkadaşların 'o bölümde ne oluyor, anlat' diye itiraz açar, diğer oyuncuların çoğunluğu itiraz ederse giriş silinir.",
    proofRequired: true,
    category: "zihin",
    maxPerEntry: 300,
    maxPerDay: 500,
  },
  {
    key: "dil_pratigi",
    nameTr: "Dil Pratiği Dakikası",
    emoji: "🔤",
    metricType: "manual_count",
    unitTr: "dk",
    direction: "higher",
    descriptionTr: "Kaç dakika dil çalıştıysan gir, uygulamandan ekran görüntüsünü de at. En çok dakika toplayan kazanır.",
    descriptionPoliteTr: "Her gün yabancı dil çalışma dakikanızı girin ve dil uygulamanızdan ekran görüntüsü ekleyin. En çok dakika toplayan kazanır.",
    howMeasuredTr: "Dakikayı sen giriyorsun, uygulama günün toplamını tutuyor. Fotoğraf kanıtı açıksa (bu tipte varsayılan açık) girişe dil uygulamandan o günün ilerlemesini gösteren bir ekran görüntüsü ekliyorsun; görüntü dakikayı değil o gün çalıştığını gösteriyor. Tek girişte en fazla 120, günde en fazla 240 dakika yazılır.",
    defaultDurationDays: 14,
    suggestedRewardTr: "Kaybeden kazananın dil uygulaması aboneliğini bir ay öder.",
    antiCheatTr: "Hile: uygulamayı açık bırakıp dakika saymak, eski ekran görüntüsü, 5 dk çalışıp 120 yazmak. Caydırma: tek girişte 120, günde 240 dk tavanı; ekran görüntüsünü arkadaşların görür, 10 XP'ye 120 dakika yazdıysan itiraz açar, diğer oyuncuların çoğunluğu itiraz ederse giriş silinir.",
    proofRequired: true,
    category: "zihin",
    maxPerEntry: 120,
    maxPerDay: 240,
  },
  {
    key: "gunluk_yazma",
    nameTr: "Günlük Defteri",
    emoji: "📝",
    metricType: "daily_boolean",
    unitTr: "gün",
    direction: "higher",
    descriptionTr: "Her gün en az yarım sayfa yazıp 'Yaptım' diyorsun. 'Bugün iyiydi' yazıp kapatmak olmuyor, en çok yazılı gün toplayan kazanır.",
    descriptionPoliteTr: "Her gün en az yarım sayfa günlük yazın ve işaretleyin. En çok yazılı gün toplayan kazanır.",
    howMeasuredTr: "Her gün 'Yaptım' ya da 'Yapmadım' diye işaretliyorsun, dünü de sonradan işaretleyebilirsin. Fotoğraf yok, yazdıklarını kimse görmüyor; işaretlemediğin gün yazmamış sayılıyorsun.",
    defaultDurationDays: 14,
    suggestedRewardTr: "Kaybeden kazanana güzel bir defter alır.",
    antiCheatTr: "Hile: iki satır yazıp 'yazdım' demek. Caydırma: uygulamanın defterini görme şansı yok, iş dürüstlüğe ve arkadaşlara kalıyor; inanmayan itiraz açar, diğer oyuncuların çoğunluğu itiraz ederse gün düşer.",
    proofRequired: false,
    category: "zihin",
    maxPerEntry: 1,
    maxPerDay: 1,
  },
  {
    key: "sigara_yok",
    nameTr: "Dumansız Günler",
    emoji: "🚭",
    metricType: "daily_boolean",
    unitTr: "gün",
    direction: "higher",
    descriptionTr: "Her gün içmediğini işaretliyorsun. Bir tane bile çektiysen o gün gitti, en çok temiz gün toplayan kazanır.",
    descriptionPoliteTr: "Her gün sigara içmediğinizi işaretleyin. En çok temiz gün toplayan kazanır, zor olduğunu biliyoruz.",
    howMeasuredTr: "Her gün içtim ya da içmedim diye işaretliyorsun, işaretlemediğin gün içmiş sayılıyorsun. Uygulamanın bunu doğrulama şansı yok, sadece arkadaşların itiraz edebiliyor.",
    defaultDurationDays: 14,
    suggestedRewardTr: "Kaybeden kazanana bir aylık sigara parası kadar hediye alır.",
    antiCheatTr: "Hile: gizli içmek. Caydırma: dürüstlük ve arkadaş itirazı; story'de ya da balkonda elinde sigarayla görülürsen itiraz açılır, diğer oyuncuların çoğunluğu itiraz ederse gün düşer. Yalan söyleyen kendi kendine koymuş olur.",
    proofRequired: false,
    category: "kotu_aliskanlik",
    maxPerEntry: 1,
    maxPerDay: 1,
  },
  {
    key: "alkol_yok",
    nameTr: "Ayık Kalma Yarışı",
    emoji: "🍺",
    metricType: "daily_boolean",
    unitTr: "gün",
    direction: "higher",
    descriptionTr: "Her gün içmediğini işaretliyorsun, en çok ayık gün toplayan kazanır. 'Cuma akşamı bir bira bir şey olmaz' diyen o günü kaybeder.",
    descriptionPoliteTr: "Her gün alkol almadığınızı işaretleyin. En çok temiz gün toplayan kazanır.",
    howMeasuredTr: "Her gün 'Yaptım' ya da 'Yapmadım' diye işaretliyorsun, dünü de sonradan işaretleyebilirsin. İşaretlemediğin gün ayık gün sayılmıyor; fotoğraf adımı yok, iş dürüstlüğe ve arkadaşlara kalıyor.",
    defaultDurationDays: 14,
    suggestedRewardTr: "Kaybeden bir sonraki buluşmada alkolsüz içecekleri ısmarlar.",
    antiCheatTr: "Hile: gizli içmek, işaretlemeyi 'unutmak'. Caydırma: işaretlenmeyen gün zaten sayılmıyor; arkadaşların story'de bardağı görürse itiraz açar, diğer oyuncuların çoğunluğu itiraz ederse gün düşer.",
    proofRequired: false,
    category: "kotu_aliskanlik",
    maxPerEntry: 1,
    maxPerDay: 1,
  },
  {
    key: "tirnak_yeme_yok",
    nameTr: "Tırnak Yemeyen Koyar",
    emoji: "💅",
    metricType: "daily_boolean",
    unitTr: "gün",
    direction: "higher",
    descriptionTr: "Her gün tırnak yemediğini işaretliyorsun, en çok temiz gün toplayan kazanır. Ellerini gören arkadaşın 'bunlar yenmiş' derse itiraz gelir.",
    descriptionPoliteTr: "Her gün tırnak yemediğinizi işaretleyin. En çok temiz gün toplayan kazanır.",
    howMeasuredTr: "Her gün 'Yaptım' ya da 'Yapmadım' diye işaretliyorsun, dünü de sonradan işaretleyebilirsin. Fotoğraf adımı yok, uygulama ellerini göremiyor; işaretlemediğin gün temiz gün sayılmıyor.",
    defaultDurationDays: 14,
    suggestedRewardTr: "Kaybeden kazanana el kremi ve tırnak makası alır.",
    antiCheatTr: "Hile: işaretleyip kemirmeye devam etmek. Caydırma: dürüstlük ve arkadaşlar; tırnaklarını gören biri itiraz açar, diğer oyuncuların çoğunluğu itiraz ederse o gün düşer.",
    proofRequired: false,
    category: "kotu_aliskanlik",
    maxPerEntry: 1,
    maxPerDay: 1,
  },
  {
    key: "soguk_dus",
    nameTr: "Soğuk Duş Kahramanı",
    emoji: "🥶",
    metricType: "daily_boolean",
    unitTr: "gün",
    direction: "higher",
    descriptionTr: "Her sabah en az bir dakika soğuk su, bağırmak serbest. Her gün işaretliyorsun, en çok gün toplayan kazanır.",
    descriptionPoliteTr: "Her gün en az bir dakika soğuk duş alın ve işaretleyin. En çok gün toplayan kazanır.",
    howMeasuredTr: "Her gün 'Yaptım' ya da 'Yapmadım' diye işaretliyorsun, dünü de sonradan işaretleyebilirsin. Fotoğraf ya da video adımı yok, işaretlemediğin gün almamış sayılıyorsun.",
    defaultDurationDays: 7,
    suggestedRewardTr: "Kaybeden kazanana üstünde KOYDUM yazan bir havlu alır.",
    antiCheatTr: "Hile: işaretleyip duş almamak, ılık suya 'soğuk' demek. Caydırma: uygulamanın suyun sıcaklığını bilme şansı yok, iş dürüstlüğe ve arkadaşlara kalıyor; inanmayan itiraz açar, diğer oyuncuların çoğunluğu itiraz ederse gün düşer.",
    proofRequired: false,
    category: "diger",
    maxPerEntry: 1,
    maxPerDay: 1,
  },
  {
    key: "yatak_toplama",
    nameTr: "Yatak Toplama Sabahı",
    emoji: "🛌",
    metricType: "checkin_deadline",
    unitTr: "gün",
    direction: "higher",
    descriptionTr: "Her sabah dokuzdan önce yatağını toplayıp 'Geldim' diyorsun. Fotoğraf yok, sözüne güveniyoruz; en çok düzenli sabah toplayan kazanır.",
    descriptionPoliteTr: "Her sabah belirlenen saatten önce yatağınızı toplayıp uygulamadan check-in yapın. En çok başarılı sabah toplayan kazanır.",
    howMeasuredTr: "Yatağı toplayınca 'Geldim' butonuna basıyorsun, günde bir kere; saate sunucu bakıyor, senin saat diliminde. 05:00'ten önce basılan check-in kabul edilmiyor, saatinden sonra basılan o gün için sıfır. Fotoğraf adımı yok.",
    defaultDurationDays: 7,
    defaultDeadlineTime: "09:00",
    checkinWindowStart: "05:00",
    suggestedRewardTr: "Kaybeden kazananın evinde bir kere yatağı toplar.",
    antiCheatTr: "Hile: toplamadan basmak, hiç uyunmamış yatak. Caydırma: sunucu saati, en erken 05:00, günde tek check-in; yatağı uygulama göremiyor, eve gelen arkadaşın görür ve itiraz açar, diğer oyuncuların çoğunluğu itiraz ederse gün düşer.",
    proofRequired: false,
    category: "diger",
    maxPerEntry: 1,
    maxPerDay: 1,
  },
] as const;

const BY_KEY: Record<string, ChallengeType> = Object.fromEntries(
  CHALLENGE_TYPES.map((type) => [type.key, type])
);

export function getChallengeType(key: string): ChallengeType | undefined {
  return BY_KEY[key];
}

/** Throws when the key is unknown — used on paths where the key came from the DB. */
export function requireChallengeType(key: string): ChallengeType {
  const type = BY_KEY[key];
  if (!type) throw new Error(`Unknown challenge type: ${key}`);
  return type;
}

export function challengeTypesByCategory(): Record<string, ChallengeType[]> {
  const grouped: Record<string, ChallengeType[]> = {};
  for (const type of CHALLENGE_TYPES) {
    (grouped[type.category] ??= []).push(type);
  }
  return grouped;
}

export function challengeTypesForMetric(metricType: MetricType): ChallengeType[] {
  return CHALLENGE_TYPES.filter((type) => type.metricType === metricType);
}

/** The catalog types a given phone reading fills in (`deviceMetric`). */
export function challengeTypesForDevice(metric: DeviceMetric): ChallengeType[] {
  return CHALLENGE_TYPES.filter((type) => type.deviceMetric === metric);
}

/** Turkish labels for the catalog categories, in display order. */
export const CATEGORY_LABELS_TR: Record<string, string> = {
  hareket: 'Hareket',
  ekran: 'Ekran',
  uyku: 'Uyku',
  beslenme: 'Beslenme',
  zihin: 'Zihin',
  kotu_aliskanlik: 'Kötü Alışkanlık',
  diger: 'Diğer',
};

export const CATEGORY_ORDER = [
  'hareket',
  'ekran',
  'uyku',
  'beslenme',
  'zihin',
  'kotu_aliskanlik',
  'diger',
] as const;
